//
// add_seq_dispatch.c - Unified dispatch for hardcoded addition sequences
//
// Generated by scripts/generate_seq_all.py - DO NOT EDIT MANUALLY
//
// Routes get_hardcoded_*_add(bits) calls to per-width implementations.
// Each per-width file is conditionally compiled via #ifdef SEQ_WIDTH_N.
//

#include "sequences.h"
#include <stddef.h>

// ============================================================================
// FORWARD DECLARATIONS (conditionally compiled per width)
// ============================================================================

#ifdef SEQ_WIDTH_1
const sequence_t *get_hardcoded_QQ_add_1(int bits);
const sequence_t *get_hardcoded_cQQ_add_1(int bits);
sequence_t *get_hardcoded_CQ_add_1(int bits);
sequence_t *get_hardcoded_cCQ_add_1(int bits);
#endif

#ifdef SEQ_WIDTH_2
const sequence_t *get_hardcoded_QQ_add_2(int bits);
const sequence_t *get_hardcoded_cQQ_add_2(int bits);
sequence_t *get_hardcoded_CQ_add_2(int bits);
sequence_t *get_hardcoded_cCQ_add_2(int bits);
#endif

#ifdef SEQ_WIDTH_3
const sequence_t *get_hardcoded_QQ_add_3(int bits);
const sequence_t *get_hardcoded_cQQ_add_3(int bits);
sequence_t *get_hardcoded_CQ_add_3(int bits);
sequence_t *get_hardcoded_cCQ_add_3(int bits);
#endif

#ifdef SEQ_WIDTH_4
const sequence_t *get_hardcoded_QQ_add_4(int bits);
const sequence_t *get_hardcoded_cQQ_add_4(int bits);
sequence_t *get_hardcoded_CQ_add_4(int bits);
sequence_t *get_hardcoded_cCQ_add_4(int bits);
#endif

#ifdef SEQ_WIDTH_5
const sequence_t *get_hardcoded_QQ_add_5(int bits);
const sequence_t *get_hardcoded_cQQ_add_5(int bits);
sequence_t *get_hardcoded_CQ_add_5(int bits);
sequence_t *get_hardcoded_cCQ_add_5(int bits);
#endif

#ifdef SEQ_WIDTH_6
const sequence_t *get_hardcoded_QQ_add_6(int bits);
const sequence_t *get_hardcoded_cQQ_add_6(int bits);
sequence_t *get_hardcoded_CQ_add_6(int bits);
sequence_t *get_hardcoded_cCQ_add_6(int bits);
#endif

#ifdef SEQ_WIDTH_7
const sequence_t *get_hardcoded_QQ_add_7(int bits);
const sequence_t *get_hardcoded_cQQ_add_7(int bits);
sequence_t *get_hardcoded_CQ_add_7(int bits);
sequence_t *get_hardcoded_cCQ_add_7(int bits);
#endif

#ifdef SEQ_WIDTH_8
const sequence_t *get_hardcoded_QQ_add_8(int bits);
const sequence_t *get_hardcoded_cQQ_add_8(int bits);
sequence_t *get_hardcoded_CQ_add_8(int bits);
sequence_t *get_hardcoded_cCQ_add_8(int bits);
#endif

#ifdef SEQ_WIDTH_9
const sequence_t *get_hardcoded_QQ_add_9(int bits);
const sequence_t *get_hardcoded_cQQ_add_9(int bits);
sequence_t *get_hardcoded_CQ_add_9(int bits);
sequence_t *get_hardcoded_cCQ_add_9(int bits);
#endif

#ifdef SEQ_WIDTH_10
const sequence_t *get_hardcoded_QQ_add_10(int bits);
const sequence_t *get_hardcoded_cQQ_add_10(int bits);
sequence_t *get_hardcoded_CQ_add_10(int bits);
sequence_t *get_hardcoded_cCQ_add_10(int bits);
#endif

#ifdef SEQ_WIDTH_11
const sequence_t *get_hardcoded_QQ_add_11(int bits);
const sequence_t *get_hardcoded_cQQ_add_11(int bits);
sequence_t *get_hardcoded_CQ_add_11(int bits);
sequence_t *get_hardcoded_cCQ_add_11(int bits);
#endif

#ifdef SEQ_WIDTH_12
const sequence_t *get_hardcoded_QQ_add_12(int bits);
const sequence_t *get_hardcoded_cQQ_add_12(int bits);
sequence_t *get_hardcoded_CQ_add_12(int bits);
sequence_t *get_hardcoded_cCQ_add_12(int bits);
#endif

#ifdef SEQ_WIDTH_13
const sequence_t *get_hardcoded_QQ_add_13(int bits);
const sequence_t *get_hardcoded_cQQ_add_13(int bits);
sequence_t *get_hardcoded_CQ_add_13(int bits);
sequence_t *get_hardcoded_cCQ_add_13(int bits);
#endif

#ifdef SEQ_WIDTH_14
const sequence_t *get_hardcoded_QQ_add_14(int bits);
const sequence_t *get_hardcoded_cQQ_add_14(int bits);
sequence_t *get_hardcoded_CQ_add_14(int bits);
sequence_t *get_hardcoded_cCQ_add_14(int bits);
#endif

#ifdef SEQ_WIDTH_15
const sequence_t *get_hardcoded_QQ_add_15(int bits);
const sequence_t *get_hardcoded_cQQ_add_15(int bits);
sequence_t *get_hardcoded_CQ_add_15(int bits);
sequence_t *get_hardcoded_cCQ_add_15(int bits);
#endif

#ifdef SEQ_WIDTH_16
const sequence_t *get_hardcoded_QQ_add_16(int bits);
const sequence_t *get_hardcoded_cQQ_add_16(int bits);
sequence_t *get_hardcoded_CQ_add_16(int bits);
sequence_t *get_hardcoded_cCQ_add_16(int bits);
#endif

// ============================================================================
// UNIFIED QQ_add DISPATCH
// ============================================================================

const sequence_t *get_hardcoded_QQ_add(int bits) {
    switch (bits) {
#ifdef SEQ_WIDTH_1
    case 1:
        return get_hardcoded_QQ_add_1(bits);
#endif
#ifdef SEQ_WIDTH_2
    case 2:
        return get_hardcoded_QQ_add_2(bits);
#endif
#ifdef SEQ_WIDTH_3
    case 3:
        return get_hardcoded_QQ_add_3(bits);
#endif
#ifdef SEQ_WIDTH_4
    case 4:
        return get_hardcoded_QQ_add_4(bits);
#endif
#ifdef SEQ_WIDTH_5
    case 5:
        return get_hardcoded_QQ_add_5(bits);
#endif
#ifdef SEQ_WIDTH_6
    case 6:
        return get_hardcoded_QQ_add_6(bits);
#endif
#ifdef SEQ_WIDTH_7
    case 7:
        return get_hardcoded_QQ_add_7(bits);
#endif
#ifdef SEQ_WIDTH_8
    case 8:
        return get_hardcoded_QQ_add_8(bits);
#endif
#ifdef SEQ_WIDTH_9
    case 9:
        return get_hardcoded_QQ_add_9(bits);
#endif
#ifdef SEQ_WIDTH_10
    case 10:
        return get_hardcoded_QQ_add_10(bits);
#endif
#ifdef SEQ_WIDTH_11
    case 11:
        return get_hardcoded_QQ_add_11(bits);
#endif
#ifdef SEQ_WIDTH_12
    case 12:
        return get_hardcoded_QQ_add_12(bits);
#endif
#ifdef SEQ_WIDTH_13
    case 13:
        return get_hardcoded_QQ_add_13(bits);
#endif
#ifdef SEQ_WIDTH_14
    case 14:
        return get_hardcoded_QQ_add_14(bits);
#endif
#ifdef SEQ_WIDTH_15
    case 15:
        return get_hardcoded_QQ_add_15(bits);
#endif
#ifdef SEQ_WIDTH_16
    case 16:
        return get_hardcoded_QQ_add_16(bits);
#endif
    default:
        return NULL;
    }
}

// ============================================================================
// UNIFIED cQQ_add DISPATCH
// ============================================================================

const sequence_t *get_hardcoded_cQQ_add(int bits) {
    switch (bits) {
#ifdef SEQ_WIDTH_1
    case 1:
        return get_hardcoded_cQQ_add_1(bits);
#endif
#ifdef SEQ_WIDTH_2
    case 2:
        return get_hardcoded_cQQ_add_2(bits);
#endif
#ifdef SEQ_WIDTH_3
    case 3:
        return get_hardcoded_cQQ_add_3(bits);
#endif
#ifdef SEQ_WIDTH_4
    case 4:
        return get_hardcoded_cQQ_add_4(bits);
#endif
#ifdef SEQ_WIDTH_5
    case 5:
        return get_hardcoded_cQQ_add_5(bits);
#endif
#ifdef SEQ_WIDTH_6
    case 6:
        return get_hardcoded_cQQ_add_6(bits);
#endif
#ifdef SEQ_WIDTH_7
    case 7:
        return get_hardcoded_cQQ_add_7(bits);
#endif
#ifdef SEQ_WIDTH_8
    case 8:
        return get_hardcoded_cQQ_add_8(bits);
#endif
#ifdef SEQ_WIDTH_9
    case 9:
        return get_hardcoded_cQQ_add_9(bits);
#endif
#ifdef SEQ_WIDTH_10
    case 10:
        return get_hardcoded_cQQ_add_10(bits);
#endif
#ifdef SEQ_WIDTH_11
    case 11:
        return get_hardcoded_cQQ_add_11(bits);
#endif
#ifdef SEQ_WIDTH_12
    case 12:
        return get_hardcoded_cQQ_add_12(bits);
#endif
#ifdef SEQ_WIDTH_13
    case 13:
        return get_hardcoded_cQQ_add_13(bits);
#endif
#ifdef SEQ_WIDTH_14
    case 14:
        return get_hardcoded_cQQ_add_14(bits);
#endif
#ifdef SEQ_WIDTH_15
    case 15:
        return get_hardcoded_cQQ_add_15(bits);
#endif
#ifdef SEQ_WIDTH_16
    case 16:
        return get_hardcoded_cQQ_add_16(bits);
#endif
    default:
        return NULL;
    }
}

// ============================================================================
// UNIFIED CQ_add DISPATCH (mutable return for angle injection)
// ============================================================================

sequence_t *get_hardcoded_CQ_add(int bits) {
    switch (bits) {
#ifdef SEQ_WIDTH_1
    case 1:
        return get_hardcoded_CQ_add_1(bits);
#endif
#ifdef SEQ_WIDTH_2
    case 2:
        return get_hardcoded_CQ_add_2(bits);
#endif
#ifdef SEQ_WIDTH_3
    case 3:
        return get_hardcoded_CQ_add_3(bits);
#endif
#ifdef SEQ_WIDTH_4
    case 4:
        return get_hardcoded_CQ_add_4(bits);
#endif
#ifdef SEQ_WIDTH_5
    case 5:
        return get_hardcoded_CQ_add_5(bits);
#endif
#ifdef SEQ_WIDTH_6
    case 6:
        return get_hardcoded_CQ_add_6(bits);
#endif
#ifdef SEQ_WIDTH_7
    case 7:
        return get_hardcoded_CQ_add_7(bits);
#endif
#ifdef SEQ_WIDTH_8
    case 8:
        return get_hardcoded_CQ_add_8(bits);
#endif
#ifdef SEQ_WIDTH_9
    case 9:
        return get_hardcoded_CQ_add_9(bits);
#endif
#ifdef SEQ_WIDTH_10
    case 10:
        return get_hardcoded_CQ_add_10(bits);
#endif
#ifdef SEQ_WIDTH_11
    case 11:
        return get_hardcoded_CQ_add_11(bits);
#endif
#ifdef SEQ_WIDTH_12
    case 12:
        return get_hardcoded_CQ_add_12(bits);
#endif
#ifdef SEQ_WIDTH_13
    case 13:
        return get_hardcoded_CQ_add_13(bits);
#endif
#ifdef SEQ_WIDTH_14
    case 14:
        return get_hardcoded_CQ_add_14(bits);
#endif
#ifdef SEQ_WIDTH_15
    case 15:
        return get_hardcoded_CQ_add_15(bits);
#endif
#ifdef SEQ_WIDTH_16
    case 16:
        return get_hardcoded_CQ_add_16(bits);
#endif
    default:
        return NULL;
    }
}

// ============================================================================
// UNIFIED cCQ_add DISPATCH (mutable return for angle injection)
// ============================================================================

sequence_t *get_hardcoded_cCQ_add(int bits) {
    switch (bits) {
#ifdef SEQ_WIDTH_1
    case 1:
        return get_hardcoded_cCQ_add_1(bits);
#endif
#ifdef SEQ_WIDTH_2
    case 2:
        return get_hardcoded_cCQ_add_2(bits);
#endif
#ifdef SEQ_WIDTH_3
    case 3:
        return get_hardcoded_cCQ_add_3(bits);
#endif
#ifdef SEQ_WIDTH_4
    case 4:
        return get_hardcoded_cCQ_add_4(bits);
#endif
#ifdef SEQ_WIDTH_5
    case 5:
        return get_hardcoded_cCQ_add_5(bits);
#endif
#ifdef SEQ_WIDTH_6
    case 6:
        return get_hardcoded_cCQ_add_6(bits);
#endif
#ifdef SEQ_WIDTH_7
    case 7:
        return get_hardcoded_cCQ_add_7(bits);
#endif
#ifdef SEQ_WIDTH_8
    case 8:
        return get_hardcoded_cCQ_add_8(bits);
#endif
#ifdef SEQ_WIDTH_9
    case 9:
        return get_hardcoded_cCQ_add_9(bits);
#endif
#ifdef SEQ_WIDTH_10
    case 10:
        return get_hardcoded_cCQ_add_10(bits);
#endif
#ifdef SEQ_WIDTH_11
    case 11:
        return get_hardcoded_cCQ_add_11(bits);
#endif
#ifdef SEQ_WIDTH_12
    case 12:
        return get_hardcoded_cCQ_add_12(bits);
#endif
#ifdef SEQ_WIDTH_13
    case 13:
        return get_hardcoded_cCQ_add_13(bits);
#endif
#ifdef SEQ_WIDTH_14
    case 14:
        return get_hardcoded_cCQ_add_14(bits);
#endif
#ifdef SEQ_WIDTH_15
    case 15:
        return get_hardcoded_cCQ_add_15(bits);
#endif
#ifdef SEQ_WIDTH_16
    case 16:
        return get_hardcoded_cCQ_add_16(bits);
#endif
    default:
        return NULL;
    }
}
