//
// add_seq_1.c - Hardcoded addition sequences for 1-bit width
//
// Generated by scripts/generate_seq_all.py - DO NOT EDIT MANUALLY
//
// Contains: QQ_add, cQQ_add (static const), CQ_add, cCQ_add (template-init)
// Shared QFT/IQFT: static const arrays shared between QQ_add and cQQ_add,
//                  init helpers shared between CQ_add and cCQ_add
//

#include "sequences.h"

#ifdef SEQ_WIDTH_1

#include <stdlib.h>

// SEQ_PI as compile-time constant for static initializers
// (math.h M_PI is not a constant expression in standard C)
#ifndef SEQ_PI
#define SEQ_PI 3.14159265358979323846
#endif

// ============================================================================
// SHARED QFT LAYERS WIDTH 1 (1 layers)
// Used by QQ_ADD and cQQ_ADD composite LAYERS arrays
// ============================================================================

static const gate_t SHARED_QFT_1_L0[] = {{.Gate = H,
                                          .Target = 0,
                                          .NumControls = 0,
                                          .Control = {0},
                                          .large_control = NULL,
                                          .GateValue = 0,
                                          .NumBasisGates = 0}};

// ============================================================================
// SHARED IQFT LAYERS WIDTH 1 (1 layers)
// Used by QQ_ADD and cQQ_ADD composite LAYERS arrays
// ============================================================================

static const gate_t SHARED_IQFT_1_L0[] = {{.Gate = H,
                                           .Target = 0,
                                           .NumControls = 0,
                                           .Control = {0},
                                           .large_control = NULL,
                                           .GateValue = 0,
                                           .NumBasisGates = 0}};

// ============================================================================
// QQ_ADD WIDTH 1 (3 layers)
// Qubit layout: [0,0] = target, [1,1] = control
// ============================================================================

static const gate_t QQ_ADD_MID_1_L0[] = {{.Gate = P,
                                          .Target = 0,
                                          .NumControls = 1,
                                          .Control = {1},
                                          .large_control = NULL,
                                          .GateValue = SEQ_PI,
                                          .NumBasisGates = 0}};

static const gate_t *QQ_ADD_1_LAYERS[] = {SHARED_QFT_1_L0, QQ_ADD_MID_1_L0, SHARED_IQFT_1_L0};
static const num_t QQ_ADD_1_GPL[] = {1, 1, 1};

static const sequence_t HARDCODED_QQ_ADD_1 = {.seq = (gate_t **)QQ_ADD_1_LAYERS,
                                              .num_layer = 3,
                                              .used_layer = 3,
                                              .gates_per_layer = (num_t *)QQ_ADD_1_GPL};

// ============================================================================
// cQQ_ADD WIDTH 1 (7 layers)
// Qubit layout: [0,0] = target, [1,1] = b, [2] = control
// ============================================================================

static const gate_t cQQ_ADD_MID_1_L0[] = {{.Gate = P,
                                           .Target = 0,
                                           .NumControls = 1,
                                           .Control = {2},
                                           .large_control = NULL,
                                           .GateValue = SEQ_PI / 2,
                                           .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_1_L1[] = {{.Gate = X,
                                           .Target = 1,
                                           .NumControls = 1,
                                           .Control = {2},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_1_L2[] = {{.Gate = P,
                                           .Target = 0,
                                           .NumControls = 1,
                                           .Control = {1},
                                           .large_control = NULL,
                                           .GateValue = -SEQ_PI / 2,
                                           .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_1_L3[] = {{.Gate = X,
                                           .Target = 1,
                                           .NumControls = 1,
                                           .Control = {2},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t cQQ_ADD_MID_1_L4[] = {{.Gate = P,
                                           .Target = 0,
                                           .NumControls = 1,
                                           .Control = {1},
                                           .large_control = NULL,
                                           .GateValue = SEQ_PI / 2,
                                           .NumBasisGates = 0}};

static const gate_t *cQQ_ADD_1_LAYERS[] = {SHARED_QFT_1_L0,  cQQ_ADD_MID_1_L0, cQQ_ADD_MID_1_L1,
                                           cQQ_ADD_MID_1_L2, cQQ_ADD_MID_1_L3, cQQ_ADD_MID_1_L4,
                                           SHARED_IQFT_1_L0};
static const num_t cQQ_ADD_1_GPL[] = {1, 1, 1, 1, 1, 1, 1};

static const sequence_t HARDCODED_cQQ_ADD_1 = {.seq = (gate_t **)cQQ_ADD_1_LAYERS,
                                               .num_layer = 7,
                                               .used_layer = 7,
                                               .gates_per_layer = (num_t *)cQQ_ADD_1_GPL};

// ============================================================================
// SHARED QFT/IQFT INIT HELPERS WIDTH 1
// Used by CQ_ADD and cCQ_ADD template-init functions
// ============================================================================

static void init_shared_qft_layers_1(sequence_t *seq, int start_layer) {
    // QFT Layer 0
    seq->gates_per_layer[start_layer + 0] = 1;
    seq->seq[start_layer + 0] = calloc(1, sizeof(gate_t));
    seq->seq[start_layer + 0][0] = (gate_t){.Gate = H,
                                            .Target = 0,
                                            .NumControls = 0,
                                            .Control = {0},
                                            .large_control = NULL,
                                            .GateValue = 0,
                                            .NumBasisGates = 0};
}

static void init_shared_iqft_layers_1(sequence_t *seq, int start_layer) {
    // IQFT Layer 0
    seq->gates_per_layer[start_layer + 0] = 1;
    seq->seq[start_layer + 0] = calloc(1, sizeof(gate_t));
    seq->seq[start_layer + 0][0] = (gate_t){.Gate = H,
                                            .Target = 0,
                                            .NumControls = 0,
                                            .Control = {0},
                                            .large_control = NULL,
                                            .GateValue = 0,
                                            .NumBasisGates = 0};
}

// ============================================================================
// CQ_ADD WIDTH 1 (template-init, 3 layers)
// Qubit layout: [0,0] = target, classical value injected at runtime
// ============================================================================

static sequence_t *cached_CQ_add_1 = NULL;

sequence_t *init_hardcoded_CQ_add_1(void) {
    if (cached_CQ_add_1 != NULL)
        return cached_CQ_add_1;

    sequence_t *seq = malloc(sizeof(sequence_t));
    if (seq == NULL)
        return NULL;
    seq->num_layer = 3;
    seq->used_layer = 3;
    seq->gates_per_layer = calloc(3, sizeof(num_t));
    seq->seq = calloc(3, sizeof(gate_t *));
    if (seq->gates_per_layer == NULL || seq->seq == NULL) {
        free(seq->gates_per_layer);
        free(seq->seq);
        free(seq);
        return NULL;
    }

    // QFT layers (shared helper)
    init_shared_qft_layers_1(seq, 0);

    // Rotation Layer 1
    seq->gates_per_layer[1] = 1;
    seq->seq[1] = calloc(1, sizeof(gate_t));
    seq->seq[1][0] = (gate_t){.Gate = P,
                              .Target = 0,
                              .NumControls = 0,
                              .Control = {0},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};

    // IQFT layers (shared helper)
    init_shared_iqft_layers_1(seq, 2);

    cached_CQ_add_1 = seq;
    return seq;
}

// ============================================================================
// cCQ_ADD WIDTH 1 (template-init, 3 layers)
// Qubit layout: [0,0] = target, [1] = control, classical value injected at runtime
// ============================================================================

static sequence_t *cached_cCQ_add_1 = NULL;

sequence_t *init_hardcoded_cCQ_add_1(void) {
    if (cached_cCQ_add_1 != NULL)
        return cached_cCQ_add_1;

    sequence_t *seq = malloc(sizeof(sequence_t));
    if (seq == NULL)
        return NULL;
    seq->num_layer = 3;
    seq->used_layer = 3;
    seq->gates_per_layer = calloc(3, sizeof(num_t));
    seq->seq = calloc(3, sizeof(gate_t *));
    if (seq->gates_per_layer == NULL || seq->seq == NULL) {
        free(seq->gates_per_layer);
        free(seq->seq);
        free(seq);
        return NULL;
    }

    // QFT layers (shared helper)
    init_shared_qft_layers_1(seq, 0);

    // Rotation Layer 1
    seq->gates_per_layer[1] = 1;
    seq->seq[1] = calloc(1, sizeof(gate_t));
    seq->seq[1][0] = (gate_t){.Gate = P,
                              .Target = 0,
                              .NumControls = 1,
                              .Control = {1},
                              .large_control = NULL,
                              .GateValue = 0,
                              .NumBasisGates = 0};

    // IQFT layers (shared helper)
    init_shared_iqft_layers_1(seq, 2);

    cached_cCQ_add_1 = seq;
    return seq;
}

// ============================================================================
// DISPATCH HELPERS FOR WIDTH 1
// ============================================================================

const sequence_t *get_hardcoded_QQ_add_1(int bits) {
    (void)bits;
    return &HARDCODED_QQ_ADD_1;
}

const sequence_t *get_hardcoded_cQQ_add_1(int bits) {
    (void)bits;
    return &HARDCODED_cQQ_ADD_1;
}

sequence_t *get_hardcoded_CQ_add_1(int bits) {
    (void)bits;
    return init_hardcoded_CQ_add_1();
}

sequence_t *get_hardcoded_cCQ_add_1(int bits) {
    (void)bits;
    return init_hardcoded_cCQ_add_1();
}

#endif // SEQ_WIDTH_1
