//
// toffoli_decomp_seq_4.c - MCX-decomposed Toffoli cQQ addition for 4-bit width
//
// Generated by scripts/generate_toffoli_decomp_seq.py - DO NOT EDIT MANUALLY
//
// Contains: Toffoli decomposed cQQ_add (static const, zero MCX)
// Algorithm: CDKM ripple-carry adder with AND-ancilla MCX decomposition
// All gates are X/CX/CCX (max 2 controls) -- no dynamic allocation needed.
//

#include "toffoli_sequences.h"

#ifdef TOFFOLI_SEQ_WIDTH_4

// ============================================================================
// TOFFOLI DECOMPOSED cQQ_ADD WIDTH 4 (40 layers)
// Qubit layout: [0,3] = target (a), [4,7] = source (b), [8] = carry, [9] = ext_ctrl, [10] = and_anc
// Total qubits: 11
// All gates: CCX (max 2 controls) -- zero MCX, zero dynamic allocation
// ============================================================================

static const gate_t TOFFOLI_DECOMP_CQQ_4_L0[] = {{.Gate = X,
                                                  .Target = 4,
                                                  .NumControls = 2,
                                                  .Control = {0, 9},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L1[] = {{.Gate = X,
                                                  .Target = 8,
                                                  .NumControls = 2,
                                                  .Control = {0, 9},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L2[] = {{.Gate = X,
                                                  .Target = 10,
                                                  .NumControls = 2,
                                                  .Control = {8, 4},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L3[] = {{.Gate = X,
                                                  .Target = 0,
                                                  .NumControls = 2,
                                                  .Control = {10, 9},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L4[] = {{.Gate = X,
                                                  .Target = 10,
                                                  .NumControls = 2,
                                                  .Control = {8, 4},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L5[] = {{.Gate = X,
                                                  .Target = 5,
                                                  .NumControls = 2,
                                                  .Control = {1, 9},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L6[] = {{.Gate = X,
                                                  .Target = 0,
                                                  .NumControls = 2,
                                                  .Control = {1, 9},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L7[] = {{.Gate = X,
                                                  .Target = 10,
                                                  .NumControls = 2,
                                                  .Control = {0, 5},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L8[] = {{.Gate = X,
                                                  .Target = 1,
                                                  .NumControls = 2,
                                                  .Control = {10, 9},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L9[] = {{.Gate = X,
                                                  .Target = 10,
                                                  .NumControls = 2,
                                                  .Control = {0, 5},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L10[] = {{.Gate = X,
                                                   .Target = 6,
                                                   .NumControls = 2,
                                                   .Control = {2, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L11[] = {{.Gate = X,
                                                   .Target = 1,
                                                   .NumControls = 2,
                                                   .Control = {2, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L12[] = {{.Gate = X,
                                                   .Target = 10,
                                                   .NumControls = 2,
                                                   .Control = {1, 6},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L13[] = {{.Gate = X,
                                                   .Target = 2,
                                                   .NumControls = 2,
                                                   .Control = {10, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L14[] = {{.Gate = X,
                                                   .Target = 10,
                                                   .NumControls = 2,
                                                   .Control = {1, 6},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L15[] = {{.Gate = X,
                                                   .Target = 7,
                                                   .NumControls = 2,
                                                   .Control = {3, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L16[] = {{.Gate = X,
                                                   .Target = 2,
                                                   .NumControls = 2,
                                                   .Control = {3, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L17[] = {{.Gate = X,
                                                   .Target = 10,
                                                   .NumControls = 2,
                                                   .Control = {2, 7},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L18[] = {{.Gate = X,
                                                   .Target = 3,
                                                   .NumControls = 2,
                                                   .Control = {10, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L19[] = {{.Gate = X,
                                                   .Target = 10,
                                                   .NumControls = 2,
                                                   .Control = {2, 7},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L20[] = {{.Gate = X,
                                                   .Target = 10,
                                                   .NumControls = 2,
                                                   .Control = {2, 7},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L21[] = {{.Gate = X,
                                                   .Target = 3,
                                                   .NumControls = 2,
                                                   .Control = {10, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L22[] = {{.Gate = X,
                                                   .Target = 10,
                                                   .NumControls = 2,
                                                   .Control = {2, 7},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L23[] = {{.Gate = X,
                                                   .Target = 2,
                                                   .NumControls = 2,
                                                   .Control = {3, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L24[] = {{.Gate = X,
                                                   .Target = 7,
                                                   .NumControls = 2,
                                                   .Control = {2, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L25[] = {{.Gate = X,
                                                   .Target = 10,
                                                   .NumControls = 2,
                                                   .Control = {1, 6},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L26[] = {{.Gate = X,
                                                   .Target = 2,
                                                   .NumControls = 2,
                                                   .Control = {10, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L27[] = {{.Gate = X,
                                                   .Target = 10,
                                                   .NumControls = 2,
                                                   .Control = {1, 6},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L28[] = {{.Gate = X,
                                                   .Target = 1,
                                                   .NumControls = 2,
                                                   .Control = {2, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L29[] = {{.Gate = X,
                                                   .Target = 6,
                                                   .NumControls = 2,
                                                   .Control = {1, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L30[] = {{.Gate = X,
                                                   .Target = 10,
                                                   .NumControls = 2,
                                                   .Control = {0, 5},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L31[] = {{.Gate = X,
                                                   .Target = 1,
                                                   .NumControls = 2,
                                                   .Control = {10, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L32[] = {{.Gate = X,
                                                   .Target = 10,
                                                   .NumControls = 2,
                                                   .Control = {0, 5},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L33[] = {{.Gate = X,
                                                   .Target = 0,
                                                   .NumControls = 2,
                                                   .Control = {1, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L34[] = {{.Gate = X,
                                                   .Target = 5,
                                                   .NumControls = 2,
                                                   .Control = {0, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L35[] = {{.Gate = X,
                                                   .Target = 10,
                                                   .NumControls = 2,
                                                   .Control = {8, 4},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L36[] = {{.Gate = X,
                                                   .Target = 0,
                                                   .NumControls = 2,
                                                   .Control = {10, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L37[] = {{.Gate = X,
                                                   .Target = 10,
                                                   .NumControls = 2,
                                                   .Control = {8, 4},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L38[] = {{.Gate = X,
                                                   .Target = 8,
                                                   .NumControls = 2,
                                                   .Control = {0, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_4_L39[] = {{.Gate = X,
                                                   .Target = 4,
                                                   .NumControls = 2,
                                                   .Control = {8, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t *TOFFOLI_DECOMP_CQQ_4_LAYERS[] = {
    TOFFOLI_DECOMP_CQQ_4_L0,  TOFFOLI_DECOMP_CQQ_4_L1,  TOFFOLI_DECOMP_CQQ_4_L2,
    TOFFOLI_DECOMP_CQQ_4_L3,  TOFFOLI_DECOMP_CQQ_4_L4,  TOFFOLI_DECOMP_CQQ_4_L5,
    TOFFOLI_DECOMP_CQQ_4_L6,  TOFFOLI_DECOMP_CQQ_4_L7,  TOFFOLI_DECOMP_CQQ_4_L8,
    TOFFOLI_DECOMP_CQQ_4_L9,  TOFFOLI_DECOMP_CQQ_4_L10, TOFFOLI_DECOMP_CQQ_4_L11,
    TOFFOLI_DECOMP_CQQ_4_L12, TOFFOLI_DECOMP_CQQ_4_L13, TOFFOLI_DECOMP_CQQ_4_L14,
    TOFFOLI_DECOMP_CQQ_4_L15, TOFFOLI_DECOMP_CQQ_4_L16, TOFFOLI_DECOMP_CQQ_4_L17,
    TOFFOLI_DECOMP_CQQ_4_L18, TOFFOLI_DECOMP_CQQ_4_L19, TOFFOLI_DECOMP_CQQ_4_L20,
    TOFFOLI_DECOMP_CQQ_4_L21, TOFFOLI_DECOMP_CQQ_4_L22, TOFFOLI_DECOMP_CQQ_4_L23,
    TOFFOLI_DECOMP_CQQ_4_L24, TOFFOLI_DECOMP_CQQ_4_L25, TOFFOLI_DECOMP_CQQ_4_L26,
    TOFFOLI_DECOMP_CQQ_4_L27, TOFFOLI_DECOMP_CQQ_4_L28, TOFFOLI_DECOMP_CQQ_4_L29,
    TOFFOLI_DECOMP_CQQ_4_L30, TOFFOLI_DECOMP_CQQ_4_L31, TOFFOLI_DECOMP_CQQ_4_L32,
    TOFFOLI_DECOMP_CQQ_4_L33, TOFFOLI_DECOMP_CQQ_4_L34, TOFFOLI_DECOMP_CQQ_4_L35,
    TOFFOLI_DECOMP_CQQ_4_L36, TOFFOLI_DECOMP_CQQ_4_L37, TOFFOLI_DECOMP_CQQ_4_L38,
    TOFFOLI_DECOMP_CQQ_4_L39};
static const num_t TOFFOLI_DECOMP_CQQ_4_GPL[] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};

static const sequence_t HARDCODED_TOFFOLI_DECOMP_CQQ_4 = {
    .seq = (gate_t **)TOFFOLI_DECOMP_CQQ_4_LAYERS,
    .num_layer = 40,
    .used_layer = 40,
    .gates_per_layer = (num_t *)TOFFOLI_DECOMP_CQQ_4_GPL};

// ============================================================================
// DISPATCH HELPER FOR WIDTH 4
// ============================================================================

const sequence_t *get_hardcoded_toffoli_decomp_cQQ_add_4(int bits) {
    (void)bits;
    return &HARDCODED_TOFFOLI_DECOMP_CQQ_4;
}

#endif // TOFFOLI_SEQ_WIDTH_4
