//
// toffoli_add_seq_5.c - Hardcoded Toffoli addition sequences for 5-bit width
//
// Generated by scripts/generate_toffoli_seq.py - DO NOT EDIT MANUALLY
//
// Contains: Toffoli QQ_add (static const), cQQ_add (dynamic init, cached)
// Algorithm: CDKM ripple-carry adder (Cuccaro et al., 2004)
//

#include "toffoli_sequences.h"

#ifdef TOFFOLI_SEQ_WIDTH_5

#include <stdlib.h>

// ============================================================================
// TOFFOLI QQ_ADD WIDTH 5 (30 layers)
// Qubit layout: [0,4] = target (a), [5,9] = source (b), [10] = ancilla
// Total qubits: 11
// ============================================================================

static const gate_t TOFFOLI_QQ_5_L0[] = {{.Gate = X,
                                          .Target = 5,
                                          .NumControls = 1,
                                          .Control = {0},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L1[] = {{.Gate = X,
                                          .Target = 10,
                                          .NumControls = 1,
                                          .Control = {0},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L2[] = {{.Gate = X,
                                          .Target = 0,
                                          .NumControls = 2,
                                          .Control = {10, 5},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L3[] = {{.Gate = X,
                                          .Target = 6,
                                          .NumControls = 1,
                                          .Control = {1},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L4[] = {{.Gate = X,
                                          .Target = 0,
                                          .NumControls = 1,
                                          .Control = {1},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L5[] = {{.Gate = X,
                                          .Target = 1,
                                          .NumControls = 2,
                                          .Control = {0, 6},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L6[] = {{.Gate = X,
                                          .Target = 7,
                                          .NumControls = 1,
                                          .Control = {2},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L7[] = {{.Gate = X,
                                          .Target = 1,
                                          .NumControls = 1,
                                          .Control = {2},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L8[] = {{.Gate = X,
                                          .Target = 2,
                                          .NumControls = 2,
                                          .Control = {1, 7},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L9[] = {{.Gate = X,
                                          .Target = 8,
                                          .NumControls = 1,
                                          .Control = {3},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L10[] = {{.Gate = X,
                                           .Target = 2,
                                           .NumControls = 1,
                                           .Control = {3},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L11[] = {{.Gate = X,
                                           .Target = 3,
                                           .NumControls = 2,
                                           .Control = {2, 8},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L12[] = {{.Gate = X,
                                           .Target = 9,
                                           .NumControls = 1,
                                           .Control = {4},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L13[] = {{.Gate = X,
                                           .Target = 3,
                                           .NumControls = 1,
                                           .Control = {4},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L14[] = {{.Gate = X,
                                           .Target = 4,
                                           .NumControls = 2,
                                           .Control = {3, 9},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L15[] = {{.Gate = X,
                                           .Target = 4,
                                           .NumControls = 2,
                                           .Control = {3, 9},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L16[] = {{.Gate = X,
                                           .Target = 3,
                                           .NumControls = 1,
                                           .Control = {4},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L17[] = {{.Gate = X,
                                           .Target = 9,
                                           .NumControls = 1,
                                           .Control = {3},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L18[] = {{.Gate = X,
                                           .Target = 3,
                                           .NumControls = 2,
                                           .Control = {2, 8},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L19[] = {{.Gate = X,
                                           .Target = 2,
                                           .NumControls = 1,
                                           .Control = {3},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L20[] = {{.Gate = X,
                                           .Target = 8,
                                           .NumControls = 1,
                                           .Control = {2},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L21[] = {{.Gate = X,
                                           .Target = 2,
                                           .NumControls = 2,
                                           .Control = {1, 7},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L22[] = {{.Gate = X,
                                           .Target = 1,
                                           .NumControls = 1,
                                           .Control = {2},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L23[] = {{.Gate = X,
                                           .Target = 7,
                                           .NumControls = 1,
                                           .Control = {1},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L24[] = {{.Gate = X,
                                           .Target = 1,
                                           .NumControls = 2,
                                           .Control = {0, 6},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L25[] = {{.Gate = X,
                                           .Target = 0,
                                           .NumControls = 1,
                                           .Control = {1},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L26[] = {{.Gate = X,
                                           .Target = 6,
                                           .NumControls = 1,
                                           .Control = {0},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L27[] = {{.Gate = X,
                                           .Target = 0,
                                           .NumControls = 2,
                                           .Control = {10, 5},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L28[] = {{.Gate = X,
                                           .Target = 10,
                                           .NumControls = 1,
                                           .Control = {0},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_5_L29[] = {{.Gate = X,
                                           .Target = 5,
                                           .NumControls = 1,
                                           .Control = {10},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t *TOFFOLI_QQ_5_LAYERS[] = {
    TOFFOLI_QQ_5_L0,  TOFFOLI_QQ_5_L1,  TOFFOLI_QQ_5_L2,  TOFFOLI_QQ_5_L3,  TOFFOLI_QQ_5_L4,
    TOFFOLI_QQ_5_L5,  TOFFOLI_QQ_5_L6,  TOFFOLI_QQ_5_L7,  TOFFOLI_QQ_5_L8,  TOFFOLI_QQ_5_L9,
    TOFFOLI_QQ_5_L10, TOFFOLI_QQ_5_L11, TOFFOLI_QQ_5_L12, TOFFOLI_QQ_5_L13, TOFFOLI_QQ_5_L14,
    TOFFOLI_QQ_5_L15, TOFFOLI_QQ_5_L16, TOFFOLI_QQ_5_L17, TOFFOLI_QQ_5_L18, TOFFOLI_QQ_5_L19,
    TOFFOLI_QQ_5_L20, TOFFOLI_QQ_5_L21, TOFFOLI_QQ_5_L22, TOFFOLI_QQ_5_L23, TOFFOLI_QQ_5_L24,
    TOFFOLI_QQ_5_L25, TOFFOLI_QQ_5_L26, TOFFOLI_QQ_5_L27, TOFFOLI_QQ_5_L28, TOFFOLI_QQ_5_L29};
static const num_t TOFFOLI_QQ_5_GPL[] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};

static const sequence_t HARDCODED_TOFFOLI_QQ_5 = {.seq = (gate_t **)TOFFOLI_QQ_5_LAYERS,
                                                  .num_layer = 30,
                                                  .used_layer = 30,
                                                  .gates_per_layer = (num_t *)TOFFOLI_QQ_5_GPL};

// ============================================================================
// TOFFOLI cQQ_ADD WIDTH 5 (30 layers)
// Qubit layout: [0,4] = target (a), [5,9] = source (b), [10] = ancilla, [11] = ext_ctrl
// Total qubits: 12
// ============================================================================

static sequence_t *cached_toffoli_cQQ_5 = NULL;

static sequence_t *init_toffoli_cQQ_5(void) {
    if (cached_toffoli_cQQ_5 != NULL)
        return cached_toffoli_cQQ_5;

    sequence_t *seq = malloc(sizeof(sequence_t));
    if (seq == NULL)
        return NULL;
    seq->num_layer = 30;
    seq->used_layer = 30;
    seq->gates_per_layer = calloc(30, sizeof(num_t));
    seq->seq = calloc(30, sizeof(gate_t *));
    if (seq->gates_per_layer == NULL || seq->seq == NULL) {
        free(seq->gates_per_layer);
        free(seq->seq);
        free(seq);
        return NULL;
    }

    // Layer 0: CCX(target=5, ctrl1=0, ctrl2=11)
    seq->gates_per_layer[0] = 1;
    seq->seq[0] = calloc(1, sizeof(gate_t));
    if (seq->seq[0] == NULL)
        goto cleanup;
    seq->seq[0][0] = (gate_t){.Gate = X,
                              .Target = 5,
                              .NumControls = 2,
                              .Control = {0, 11},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 1: CCX(target=10, ctrl1=0, ctrl2=11)
    seq->gates_per_layer[1] = 1;
    seq->seq[1] = calloc(1, sizeof(gate_t));
    if (seq->seq[1] == NULL)
        goto cleanup;
    seq->seq[1][0] = (gate_t){.Gate = X,
                              .Target = 10,
                              .NumControls = 2,
                              .Control = {0, 11},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 2: MCX(target=0, ctrls=[10,5,11])
    seq->gates_per_layer[2] = 1;
    seq->seq[2] = calloc(1, sizeof(gate_t));
    if (seq->seq[2] == NULL)
        goto cleanup;
    seq->seq[2][0].Gate = X;
    seq->seq[2][0].Target = 0;
    seq->seq[2][0].NumControls = 3;
    seq->seq[2][0].Control[0] = 10;
    seq->seq[2][0].Control[1] = 5;
    seq->seq[2][0].GateValue = 1;
    seq->seq[2][0].NumBasisGates = 0;
    seq->seq[2][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[2][0].large_control[0] = (qubit_t)10;
    seq->seq[2][0].large_control[1] = (qubit_t)5;
    seq->seq[2][0].large_control[2] = (qubit_t)11;

    // Layer 3: CCX(target=6, ctrl1=1, ctrl2=11)
    seq->gates_per_layer[3] = 1;
    seq->seq[3] = calloc(1, sizeof(gate_t));
    if (seq->seq[3] == NULL)
        goto cleanup;
    seq->seq[3][0] = (gate_t){.Gate = X,
                              .Target = 6,
                              .NumControls = 2,
                              .Control = {1, 11},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 4: CCX(target=0, ctrl1=1, ctrl2=11)
    seq->gates_per_layer[4] = 1;
    seq->seq[4] = calloc(1, sizeof(gate_t));
    if (seq->seq[4] == NULL)
        goto cleanup;
    seq->seq[4][0] = (gate_t){.Gate = X,
                              .Target = 0,
                              .NumControls = 2,
                              .Control = {1, 11},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 5: MCX(target=1, ctrls=[0,6,11])
    seq->gates_per_layer[5] = 1;
    seq->seq[5] = calloc(1, sizeof(gate_t));
    if (seq->seq[5] == NULL)
        goto cleanup;
    seq->seq[5][0].Gate = X;
    seq->seq[5][0].Target = 1;
    seq->seq[5][0].NumControls = 3;
    seq->seq[5][0].Control[0] = 0;
    seq->seq[5][0].Control[1] = 6;
    seq->seq[5][0].GateValue = 1;
    seq->seq[5][0].NumBasisGates = 0;
    seq->seq[5][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[5][0].large_control[0] = (qubit_t)0;
    seq->seq[5][0].large_control[1] = (qubit_t)6;
    seq->seq[5][0].large_control[2] = (qubit_t)11;

    // Layer 6: CCX(target=7, ctrl1=2, ctrl2=11)
    seq->gates_per_layer[6] = 1;
    seq->seq[6] = calloc(1, sizeof(gate_t));
    if (seq->seq[6] == NULL)
        goto cleanup;
    seq->seq[6][0] = (gate_t){.Gate = X,
                              .Target = 7,
                              .NumControls = 2,
                              .Control = {2, 11},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 7: CCX(target=1, ctrl1=2, ctrl2=11)
    seq->gates_per_layer[7] = 1;
    seq->seq[7] = calloc(1, sizeof(gate_t));
    if (seq->seq[7] == NULL)
        goto cleanup;
    seq->seq[7][0] = (gate_t){.Gate = X,
                              .Target = 1,
                              .NumControls = 2,
                              .Control = {2, 11},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 8: MCX(target=2, ctrls=[1,7,11])
    seq->gates_per_layer[8] = 1;
    seq->seq[8] = calloc(1, sizeof(gate_t));
    if (seq->seq[8] == NULL)
        goto cleanup;
    seq->seq[8][0].Gate = X;
    seq->seq[8][0].Target = 2;
    seq->seq[8][0].NumControls = 3;
    seq->seq[8][0].Control[0] = 1;
    seq->seq[8][0].Control[1] = 7;
    seq->seq[8][0].GateValue = 1;
    seq->seq[8][0].NumBasisGates = 0;
    seq->seq[8][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[8][0].large_control[0] = (qubit_t)1;
    seq->seq[8][0].large_control[1] = (qubit_t)7;
    seq->seq[8][0].large_control[2] = (qubit_t)11;

    // Layer 9: CCX(target=8, ctrl1=3, ctrl2=11)
    seq->gates_per_layer[9] = 1;
    seq->seq[9] = calloc(1, sizeof(gate_t));
    if (seq->seq[9] == NULL)
        goto cleanup;
    seq->seq[9][0] = (gate_t){.Gate = X,
                              .Target = 8,
                              .NumControls = 2,
                              .Control = {3, 11},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 10: CCX(target=2, ctrl1=3, ctrl2=11)
    seq->gates_per_layer[10] = 1;
    seq->seq[10] = calloc(1, sizeof(gate_t));
    if (seq->seq[10] == NULL)
        goto cleanup;
    seq->seq[10][0] = (gate_t){.Gate = X,
                               .Target = 2,
                               .NumControls = 2,
                               .Control = {3, 11},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 11: MCX(target=3, ctrls=[2,8,11])
    seq->gates_per_layer[11] = 1;
    seq->seq[11] = calloc(1, sizeof(gate_t));
    if (seq->seq[11] == NULL)
        goto cleanup;
    seq->seq[11][0].Gate = X;
    seq->seq[11][0].Target = 3;
    seq->seq[11][0].NumControls = 3;
    seq->seq[11][0].Control[0] = 2;
    seq->seq[11][0].Control[1] = 8;
    seq->seq[11][0].GateValue = 1;
    seq->seq[11][0].NumBasisGates = 0;
    seq->seq[11][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[11][0].large_control[0] = (qubit_t)2;
    seq->seq[11][0].large_control[1] = (qubit_t)8;
    seq->seq[11][0].large_control[2] = (qubit_t)11;

    // Layer 12: CCX(target=9, ctrl1=4, ctrl2=11)
    seq->gates_per_layer[12] = 1;
    seq->seq[12] = calloc(1, sizeof(gate_t));
    if (seq->seq[12] == NULL)
        goto cleanup;
    seq->seq[12][0] = (gate_t){.Gate = X,
                               .Target = 9,
                               .NumControls = 2,
                               .Control = {4, 11},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 13: CCX(target=3, ctrl1=4, ctrl2=11)
    seq->gates_per_layer[13] = 1;
    seq->seq[13] = calloc(1, sizeof(gate_t));
    if (seq->seq[13] == NULL)
        goto cleanup;
    seq->seq[13][0] = (gate_t){.Gate = X,
                               .Target = 3,
                               .NumControls = 2,
                               .Control = {4, 11},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 14: MCX(target=4, ctrls=[3,9,11])
    seq->gates_per_layer[14] = 1;
    seq->seq[14] = calloc(1, sizeof(gate_t));
    if (seq->seq[14] == NULL)
        goto cleanup;
    seq->seq[14][0].Gate = X;
    seq->seq[14][0].Target = 4;
    seq->seq[14][0].NumControls = 3;
    seq->seq[14][0].Control[0] = 3;
    seq->seq[14][0].Control[1] = 9;
    seq->seq[14][0].GateValue = 1;
    seq->seq[14][0].NumBasisGates = 0;
    seq->seq[14][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[14][0].large_control[0] = (qubit_t)3;
    seq->seq[14][0].large_control[1] = (qubit_t)9;
    seq->seq[14][0].large_control[2] = (qubit_t)11;

    // Layer 15: MCX(target=4, ctrls=[3,9,11])
    seq->gates_per_layer[15] = 1;
    seq->seq[15] = calloc(1, sizeof(gate_t));
    if (seq->seq[15] == NULL)
        goto cleanup;
    seq->seq[15][0].Gate = X;
    seq->seq[15][0].Target = 4;
    seq->seq[15][0].NumControls = 3;
    seq->seq[15][0].Control[0] = 3;
    seq->seq[15][0].Control[1] = 9;
    seq->seq[15][0].GateValue = 1;
    seq->seq[15][0].NumBasisGates = 0;
    seq->seq[15][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[15][0].large_control[0] = (qubit_t)3;
    seq->seq[15][0].large_control[1] = (qubit_t)9;
    seq->seq[15][0].large_control[2] = (qubit_t)11;

    // Layer 16: CCX(target=3, ctrl1=4, ctrl2=11)
    seq->gates_per_layer[16] = 1;
    seq->seq[16] = calloc(1, sizeof(gate_t));
    if (seq->seq[16] == NULL)
        goto cleanup;
    seq->seq[16][0] = (gate_t){.Gate = X,
                               .Target = 3,
                               .NumControls = 2,
                               .Control = {4, 11},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 17: CCX(target=9, ctrl1=3, ctrl2=11)
    seq->gates_per_layer[17] = 1;
    seq->seq[17] = calloc(1, sizeof(gate_t));
    if (seq->seq[17] == NULL)
        goto cleanup;
    seq->seq[17][0] = (gate_t){.Gate = X,
                               .Target = 9,
                               .NumControls = 2,
                               .Control = {3, 11},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 18: MCX(target=3, ctrls=[2,8,11])
    seq->gates_per_layer[18] = 1;
    seq->seq[18] = calloc(1, sizeof(gate_t));
    if (seq->seq[18] == NULL)
        goto cleanup;
    seq->seq[18][0].Gate = X;
    seq->seq[18][0].Target = 3;
    seq->seq[18][0].NumControls = 3;
    seq->seq[18][0].Control[0] = 2;
    seq->seq[18][0].Control[1] = 8;
    seq->seq[18][0].GateValue = 1;
    seq->seq[18][0].NumBasisGates = 0;
    seq->seq[18][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[18][0].large_control[0] = (qubit_t)2;
    seq->seq[18][0].large_control[1] = (qubit_t)8;
    seq->seq[18][0].large_control[2] = (qubit_t)11;

    // Layer 19: CCX(target=2, ctrl1=3, ctrl2=11)
    seq->gates_per_layer[19] = 1;
    seq->seq[19] = calloc(1, sizeof(gate_t));
    if (seq->seq[19] == NULL)
        goto cleanup;
    seq->seq[19][0] = (gate_t){.Gate = X,
                               .Target = 2,
                               .NumControls = 2,
                               .Control = {3, 11},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 20: CCX(target=8, ctrl1=2, ctrl2=11)
    seq->gates_per_layer[20] = 1;
    seq->seq[20] = calloc(1, sizeof(gate_t));
    if (seq->seq[20] == NULL)
        goto cleanup;
    seq->seq[20][0] = (gate_t){.Gate = X,
                               .Target = 8,
                               .NumControls = 2,
                               .Control = {2, 11},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 21: MCX(target=2, ctrls=[1,7,11])
    seq->gates_per_layer[21] = 1;
    seq->seq[21] = calloc(1, sizeof(gate_t));
    if (seq->seq[21] == NULL)
        goto cleanup;
    seq->seq[21][0].Gate = X;
    seq->seq[21][0].Target = 2;
    seq->seq[21][0].NumControls = 3;
    seq->seq[21][0].Control[0] = 1;
    seq->seq[21][0].Control[1] = 7;
    seq->seq[21][0].GateValue = 1;
    seq->seq[21][0].NumBasisGates = 0;
    seq->seq[21][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[21][0].large_control[0] = (qubit_t)1;
    seq->seq[21][0].large_control[1] = (qubit_t)7;
    seq->seq[21][0].large_control[2] = (qubit_t)11;

    // Layer 22: CCX(target=1, ctrl1=2, ctrl2=11)
    seq->gates_per_layer[22] = 1;
    seq->seq[22] = calloc(1, sizeof(gate_t));
    if (seq->seq[22] == NULL)
        goto cleanup;
    seq->seq[22][0] = (gate_t){.Gate = X,
                               .Target = 1,
                               .NumControls = 2,
                               .Control = {2, 11},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 23: CCX(target=7, ctrl1=1, ctrl2=11)
    seq->gates_per_layer[23] = 1;
    seq->seq[23] = calloc(1, sizeof(gate_t));
    if (seq->seq[23] == NULL)
        goto cleanup;
    seq->seq[23][0] = (gate_t){.Gate = X,
                               .Target = 7,
                               .NumControls = 2,
                               .Control = {1, 11},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 24: MCX(target=1, ctrls=[0,6,11])
    seq->gates_per_layer[24] = 1;
    seq->seq[24] = calloc(1, sizeof(gate_t));
    if (seq->seq[24] == NULL)
        goto cleanup;
    seq->seq[24][0].Gate = X;
    seq->seq[24][0].Target = 1;
    seq->seq[24][0].NumControls = 3;
    seq->seq[24][0].Control[0] = 0;
    seq->seq[24][0].Control[1] = 6;
    seq->seq[24][0].GateValue = 1;
    seq->seq[24][0].NumBasisGates = 0;
    seq->seq[24][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[24][0].large_control[0] = (qubit_t)0;
    seq->seq[24][0].large_control[1] = (qubit_t)6;
    seq->seq[24][0].large_control[2] = (qubit_t)11;

    // Layer 25: CCX(target=0, ctrl1=1, ctrl2=11)
    seq->gates_per_layer[25] = 1;
    seq->seq[25] = calloc(1, sizeof(gate_t));
    if (seq->seq[25] == NULL)
        goto cleanup;
    seq->seq[25][0] = (gate_t){.Gate = X,
                               .Target = 0,
                               .NumControls = 2,
                               .Control = {1, 11},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 26: CCX(target=6, ctrl1=0, ctrl2=11)
    seq->gates_per_layer[26] = 1;
    seq->seq[26] = calloc(1, sizeof(gate_t));
    if (seq->seq[26] == NULL)
        goto cleanup;
    seq->seq[26][0] = (gate_t){.Gate = X,
                               .Target = 6,
                               .NumControls = 2,
                               .Control = {0, 11},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 27: MCX(target=0, ctrls=[10,5,11])
    seq->gates_per_layer[27] = 1;
    seq->seq[27] = calloc(1, sizeof(gate_t));
    if (seq->seq[27] == NULL)
        goto cleanup;
    seq->seq[27][0].Gate = X;
    seq->seq[27][0].Target = 0;
    seq->seq[27][0].NumControls = 3;
    seq->seq[27][0].Control[0] = 10;
    seq->seq[27][0].Control[1] = 5;
    seq->seq[27][0].GateValue = 1;
    seq->seq[27][0].NumBasisGates = 0;
    seq->seq[27][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[27][0].large_control[0] = (qubit_t)10;
    seq->seq[27][0].large_control[1] = (qubit_t)5;
    seq->seq[27][0].large_control[2] = (qubit_t)11;

    // Layer 28: CCX(target=10, ctrl1=0, ctrl2=11)
    seq->gates_per_layer[28] = 1;
    seq->seq[28] = calloc(1, sizeof(gate_t));
    if (seq->seq[28] == NULL)
        goto cleanup;
    seq->seq[28][0] = (gate_t){.Gate = X,
                               .Target = 10,
                               .NumControls = 2,
                               .Control = {0, 11},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 29: CCX(target=5, ctrl1=10, ctrl2=11)
    seq->gates_per_layer[29] = 1;
    seq->seq[29] = calloc(1, sizeof(gate_t));
    if (seq->seq[29] == NULL)
        goto cleanup;
    seq->seq[29][0] = (gate_t){.Gate = X,
                               .Target = 5,
                               .NumControls = 2,
                               .Control = {10, 11},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    cached_toffoli_cQQ_5 = seq;
    return seq;

cleanup:
    for (int i = 0; i < 30; i++) {
        if (seq->seq[i] != NULL) {
            if (seq->seq[i][0].large_control != NULL)
                free(seq->seq[i][0].large_control);
            free(seq->seq[i]);
        }
    }
    free(seq->seq);
    free(seq->gates_per_layer);
    free(seq);
    return NULL;
}

// ============================================================================
// DISPATCH HELPERS FOR WIDTH 5
// ============================================================================

const sequence_t *get_hardcoded_toffoli_QQ_add_5(int bits) {
    (void)bits;
    return &HARDCODED_TOFFOLI_QQ_5;
}

const sequence_t *get_hardcoded_toffoli_cQQ_add_5(int bits) {
    (void)bits;
    return (const sequence_t *)init_toffoli_cQQ_5();
}

#endif // TOFFOLI_SEQ_WIDTH_5
