//
// toffoli_decomp_seq_6.c - MCX-decomposed Toffoli cQQ addition for 6-bit width
//
// Generated by scripts/generate_toffoli_decomp_seq.py - DO NOT EDIT MANUALLY
//
// Contains: Toffoli decomposed cQQ_add (static const, zero MCX)
// Algorithm: CDKM ripple-carry adder with AND-ancilla MCX decomposition
// All gates are X/CX/CCX (max 2 controls) -- no dynamic allocation needed.
//

#include "toffoli_sequences.h"

#ifdef TOFFOLI_SEQ_WIDTH_6

// ============================================================================
// TOFFOLI DECOMPOSED cQQ_ADD WIDTH 6 (60 layers)
// Qubit layout: [0,5] = target (a), [6,11] = source (b), [12] = carry, [13] = ext_ctrl, [14] =
// and_anc Total qubits: 15 All gates: CCX (max 2 controls) -- zero MCX, zero dynamic allocation
// ============================================================================

static const gate_t TOFFOLI_DECOMP_CQQ_6_L0[] = {{.Gate = X,
                                                  .Target = 6,
                                                  .NumControls = 2,
                                                  .Control = {0, 13},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L1[] = {{.Gate = X,
                                                  .Target = 12,
                                                  .NumControls = 2,
                                                  .Control = {0, 13},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L2[] = {{.Gate = X,
                                                  .Target = 14,
                                                  .NumControls = 2,
                                                  .Control = {12, 6},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L3[] = {{.Gate = X,
                                                  .Target = 0,
                                                  .NumControls = 2,
                                                  .Control = {14, 13},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L4[] = {{.Gate = X,
                                                  .Target = 14,
                                                  .NumControls = 2,
                                                  .Control = {12, 6},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L5[] = {{.Gate = X,
                                                  .Target = 7,
                                                  .NumControls = 2,
                                                  .Control = {1, 13},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L6[] = {{.Gate = X,
                                                  .Target = 0,
                                                  .NumControls = 2,
                                                  .Control = {1, 13},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L7[] = {{.Gate = X,
                                                  .Target = 14,
                                                  .NumControls = 2,
                                                  .Control = {0, 7},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L8[] = {{.Gate = X,
                                                  .Target = 1,
                                                  .NumControls = 2,
                                                  .Control = {14, 13},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L9[] = {{.Gate = X,
                                                  .Target = 14,
                                                  .NumControls = 2,
                                                  .Control = {0, 7},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L10[] = {{.Gate = X,
                                                   .Target = 8,
                                                   .NumControls = 2,
                                                   .Control = {2, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L11[] = {{.Gate = X,
                                                   .Target = 1,
                                                   .NumControls = 2,
                                                   .Control = {2, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L12[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {1, 8},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L13[] = {{.Gate = X,
                                                   .Target = 2,
                                                   .NumControls = 2,
                                                   .Control = {14, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L14[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {1, 8},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L15[] = {{.Gate = X,
                                                   .Target = 9,
                                                   .NumControls = 2,
                                                   .Control = {3, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L16[] = {{.Gate = X,
                                                   .Target = 2,
                                                   .NumControls = 2,
                                                   .Control = {3, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L17[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {2, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L18[] = {{.Gate = X,
                                                   .Target = 3,
                                                   .NumControls = 2,
                                                   .Control = {14, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L19[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {2, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L20[] = {{.Gate = X,
                                                   .Target = 10,
                                                   .NumControls = 2,
                                                   .Control = {4, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L21[] = {{.Gate = X,
                                                   .Target = 3,
                                                   .NumControls = 2,
                                                   .Control = {4, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L22[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {3, 10},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L23[] = {{.Gate = X,
                                                   .Target = 4,
                                                   .NumControls = 2,
                                                   .Control = {14, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L24[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {3, 10},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L25[] = {{.Gate = X,
                                                   .Target = 11,
                                                   .NumControls = 2,
                                                   .Control = {5, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L26[] = {{.Gate = X,
                                                   .Target = 4,
                                                   .NumControls = 2,
                                                   .Control = {5, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L27[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {4, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L28[] = {{.Gate = X,
                                                   .Target = 5,
                                                   .NumControls = 2,
                                                   .Control = {14, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L29[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {4, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L30[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {4, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L31[] = {{.Gate = X,
                                                   .Target = 5,
                                                   .NumControls = 2,
                                                   .Control = {14, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L32[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {4, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L33[] = {{.Gate = X,
                                                   .Target = 4,
                                                   .NumControls = 2,
                                                   .Control = {5, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L34[] = {{.Gate = X,
                                                   .Target = 11,
                                                   .NumControls = 2,
                                                   .Control = {4, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L35[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {3, 10},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L36[] = {{.Gate = X,
                                                   .Target = 4,
                                                   .NumControls = 2,
                                                   .Control = {14, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L37[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {3, 10},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L38[] = {{.Gate = X,
                                                   .Target = 3,
                                                   .NumControls = 2,
                                                   .Control = {4, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L39[] = {{.Gate = X,
                                                   .Target = 10,
                                                   .NumControls = 2,
                                                   .Control = {3, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L40[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {2, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L41[] = {{.Gate = X,
                                                   .Target = 3,
                                                   .NumControls = 2,
                                                   .Control = {14, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L42[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {2, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L43[] = {{.Gate = X,
                                                   .Target = 2,
                                                   .NumControls = 2,
                                                   .Control = {3, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L44[] = {{.Gate = X,
                                                   .Target = 9,
                                                   .NumControls = 2,
                                                   .Control = {2, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L45[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {1, 8},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L46[] = {{.Gate = X,
                                                   .Target = 2,
                                                   .NumControls = 2,
                                                   .Control = {14, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L47[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {1, 8},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L48[] = {{.Gate = X,
                                                   .Target = 1,
                                                   .NumControls = 2,
                                                   .Control = {2, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L49[] = {{.Gate = X,
                                                   .Target = 8,
                                                   .NumControls = 2,
                                                   .Control = {1, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L50[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {0, 7},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L51[] = {{.Gate = X,
                                                   .Target = 1,
                                                   .NumControls = 2,
                                                   .Control = {14, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L52[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {0, 7},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L53[] = {{.Gate = X,
                                                   .Target = 0,
                                                   .NumControls = 2,
                                                   .Control = {1, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L54[] = {{.Gate = X,
                                                   .Target = 7,
                                                   .NumControls = 2,
                                                   .Control = {0, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L55[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {12, 6},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L56[] = {{.Gate = X,
                                                   .Target = 0,
                                                   .NumControls = 2,
                                                   .Control = {14, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L57[] = {{.Gate = X,
                                                   .Target = 14,
                                                   .NumControls = 2,
                                                   .Control = {12, 6},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L58[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {0, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_6_L59[] = {{.Gate = X,
                                                   .Target = 6,
                                                   .NumControls = 2,
                                                   .Control = {12, 13},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t *TOFFOLI_DECOMP_CQQ_6_LAYERS[] = {
    TOFFOLI_DECOMP_CQQ_6_L0,  TOFFOLI_DECOMP_CQQ_6_L1,  TOFFOLI_DECOMP_CQQ_6_L2,
    TOFFOLI_DECOMP_CQQ_6_L3,  TOFFOLI_DECOMP_CQQ_6_L4,  TOFFOLI_DECOMP_CQQ_6_L5,
    TOFFOLI_DECOMP_CQQ_6_L6,  TOFFOLI_DECOMP_CQQ_6_L7,  TOFFOLI_DECOMP_CQQ_6_L8,
    TOFFOLI_DECOMP_CQQ_6_L9,  TOFFOLI_DECOMP_CQQ_6_L10, TOFFOLI_DECOMP_CQQ_6_L11,
    TOFFOLI_DECOMP_CQQ_6_L12, TOFFOLI_DECOMP_CQQ_6_L13, TOFFOLI_DECOMP_CQQ_6_L14,
    TOFFOLI_DECOMP_CQQ_6_L15, TOFFOLI_DECOMP_CQQ_6_L16, TOFFOLI_DECOMP_CQQ_6_L17,
    TOFFOLI_DECOMP_CQQ_6_L18, TOFFOLI_DECOMP_CQQ_6_L19, TOFFOLI_DECOMP_CQQ_6_L20,
    TOFFOLI_DECOMP_CQQ_6_L21, TOFFOLI_DECOMP_CQQ_6_L22, TOFFOLI_DECOMP_CQQ_6_L23,
    TOFFOLI_DECOMP_CQQ_6_L24, TOFFOLI_DECOMP_CQQ_6_L25, TOFFOLI_DECOMP_CQQ_6_L26,
    TOFFOLI_DECOMP_CQQ_6_L27, TOFFOLI_DECOMP_CQQ_6_L28, TOFFOLI_DECOMP_CQQ_6_L29,
    TOFFOLI_DECOMP_CQQ_6_L30, TOFFOLI_DECOMP_CQQ_6_L31, TOFFOLI_DECOMP_CQQ_6_L32,
    TOFFOLI_DECOMP_CQQ_6_L33, TOFFOLI_DECOMP_CQQ_6_L34, TOFFOLI_DECOMP_CQQ_6_L35,
    TOFFOLI_DECOMP_CQQ_6_L36, TOFFOLI_DECOMP_CQQ_6_L37, TOFFOLI_DECOMP_CQQ_6_L38,
    TOFFOLI_DECOMP_CQQ_6_L39, TOFFOLI_DECOMP_CQQ_6_L40, TOFFOLI_DECOMP_CQQ_6_L41,
    TOFFOLI_DECOMP_CQQ_6_L42, TOFFOLI_DECOMP_CQQ_6_L43, TOFFOLI_DECOMP_CQQ_6_L44,
    TOFFOLI_DECOMP_CQQ_6_L45, TOFFOLI_DECOMP_CQQ_6_L46, TOFFOLI_DECOMP_CQQ_6_L47,
    TOFFOLI_DECOMP_CQQ_6_L48, TOFFOLI_DECOMP_CQQ_6_L49, TOFFOLI_DECOMP_CQQ_6_L50,
    TOFFOLI_DECOMP_CQQ_6_L51, TOFFOLI_DECOMP_CQQ_6_L52, TOFFOLI_DECOMP_CQQ_6_L53,
    TOFFOLI_DECOMP_CQQ_6_L54, TOFFOLI_DECOMP_CQQ_6_L55, TOFFOLI_DECOMP_CQQ_6_L56,
    TOFFOLI_DECOMP_CQQ_6_L57, TOFFOLI_DECOMP_CQQ_6_L58, TOFFOLI_DECOMP_CQQ_6_L59};
static const num_t TOFFOLI_DECOMP_CQQ_6_GPL[] = {
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};

static const sequence_t HARDCODED_TOFFOLI_DECOMP_CQQ_6 = {
    .seq = (gate_t **)TOFFOLI_DECOMP_CQQ_6_LAYERS,
    .num_layer = 60,
    .used_layer = 60,
    .gates_per_layer = (num_t *)TOFFOLI_DECOMP_CQQ_6_GPL};

// ============================================================================
// DISPATCH HELPER FOR WIDTH 6
// ============================================================================

const sequence_t *get_hardcoded_toffoli_decomp_cQQ_add_6(int bits) {
    (void)bits;
    return &HARDCODED_TOFFOLI_DECOMP_CQQ_6;
}

#endif // TOFFOLI_SEQ_WIDTH_6
