//
// toffoli_cq_inc_seq_1.c - Hardcoded Toffoli CQ/cCQ increment sequences for 1-bit width
//
// Generated by plan 73-02 executor - DO NOT EDIT MANUALLY
//
// Contains: Toffoli CQ_inc (static const), cCQ_inc (dynamic init, cached)
// Algorithm: CDKM ripple-carry adder with value=1, classical-bit gate simplification
//

#include "toffoli_sequences.h"

#ifdef TOFFOLI_SEQ_WIDTH_1

#include <stdlib.h>

// ============================================================================
// TOFFOLI CQ_INC WIDTH 1 (1 layers)
// Qubit layout: [0] = self
// Total qubits: 1
// ============================================================================

static const gate_t TOFFOLI_CQ_INC_1_L0[] = {{.Gate = X,
                                              .Target = 0,
                                              .NumControls = 0,
                                              .Control = {0},
                                              .large_control = NULL,
                                              .GateValue = 1,
                                              .NumBasisGates = 0}};

static const gate_t *TOFFOLI_CQ_INC_1_LAYERS[] = {TOFFOLI_CQ_INC_1_L0};
static const num_t TOFFOLI_CQ_INC_1_GPL[] = {1};

static const sequence_t HARDCODED_TOFFOLI_CQ_INC_1 = {.seq = (gate_t **)TOFFOLI_CQ_INC_1_LAYERS,
                                                      .num_layer = 1,
                                                      .used_layer = 1,
                                                      .gates_per_layer =
                                                          (num_t *)TOFFOLI_CQ_INC_1_GPL};

// ============================================================================
// TOFFOLI cCQ_INC WIDTH 1 (1 layers)
// Qubit layout: [0] = self, [1] = ext_ctrl
// Total qubits: 2
// ============================================================================

static sequence_t *cached_toffoli_cCQ_inc_1 = NULL;

static sequence_t *init_toffoli_cCQ_inc_1(void) {
    if (cached_toffoli_cCQ_inc_1 != NULL)
        return cached_toffoli_cCQ_inc_1;

    sequence_t *seq = malloc(sizeof(sequence_t));
    if (seq == NULL)
        return NULL;
    seq->num_layer = 1;
    seq->used_layer = 1;
    seq->gates_per_layer = calloc(1, sizeof(num_t));
    seq->seq = calloc(1, sizeof(gate_t *));
    if (seq->gates_per_layer == NULL || seq->seq == NULL) {
        free(seq->gates_per_layer);
        free(seq->seq);
        free(seq);
        return NULL;
    }

    // Layer 0: CX(target=0, ctrl=1)
    seq->gates_per_layer[0] = 1;
    seq->seq[0] = calloc(1, sizeof(gate_t));
    if (seq->seq[0] == NULL)
        goto cleanup;
    seq->seq[0][0] = (gate_t){.Gate = X,
                              .Target = 0,
                              .NumControls = 1,
                              .Control = {1},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    cached_toffoli_cCQ_inc_1 = seq;
    return seq;

cleanup:
    for (int i = 0; i < 1; i++) {
        if (seq->seq[i] != NULL) {
            if (seq->seq[i][0].large_control != NULL)
                free(seq->seq[i][0].large_control);
            free(seq->seq[i]);
        }
    }
    free(seq->seq);
    free(seq->gates_per_layer);
    free(seq);
    return NULL;
}

// ============================================================================
// DISPATCH HELPERS FOR WIDTH 1
// ============================================================================

const sequence_t *get_hardcoded_toffoli_CQ_inc_1(int bits) {
    (void)bits;
    return &HARDCODED_TOFFOLI_CQ_INC_1;
}

const sequence_t *get_hardcoded_toffoli_cCQ_inc_1(int bits) {
    (void)bits;
    return (const sequence_t *)init_toffoli_cCQ_inc_1();
}

#endif // TOFFOLI_SEQ_WIDTH_1
