//
// toffoli_cq_inc_seq_4.c - Hardcoded Toffoli CQ/cCQ increment sequences for 4-bit width
//
// Generated by plan 73-02 executor - DO NOT EDIT MANUALLY
//
// Contains: Toffoli CQ_inc (static const), cCQ_inc (dynamic init, cached)
// Algorithm: CDKM ripple-carry adder with value=1, classical-bit gate simplification
//

#include "toffoli_sequences.h"

#ifdef TOFFOLI_SEQ_WIDTH_4

#include <stdlib.h>

// ============================================================================
// TOFFOLI CQ_INC WIDTH 4 (20 layers)
// Qubit layout: [0..3] = temp, [4..7] = self, [8] = carry
// Total qubits: 9
// ============================================================================

static const gate_t TOFFOLI_CQ_INC_4_L0[] = {{.Gate = X,
                                              .Target = 0,
                                              .NumControls = 0,
                                              .Control = {0},
                                              .large_control = NULL,
                                              .GateValue = 1,
                                              .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L1[] = {{.Gate = X,
                                              .Target = 4,
                                              .NumControls = 0,
                                              .Control = {0},
                                              .large_control = NULL,
                                              .GateValue = 1,
                                              .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L2[] = {{.Gate = X,
                                              .Target = 8,
                                              .NumControls = 0,
                                              .Control = {0},
                                              .large_control = NULL,
                                              .GateValue = 1,
                                              .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L3[] = {{.Gate = X,
                                              .Target = 0,
                                              .NumControls = 2,
                                              .Control = {8, 4},
                                              .large_control = NULL,
                                              .GateValue = 1,
                                              .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L4[] = {{.Gate = X,
                                              .Target = 1,
                                              .NumControls = 2,
                                              .Control = {0, 5},
                                              .large_control = NULL,
                                              .GateValue = 1,
                                              .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L5[] = {{.Gate = X,
                                              .Target = 2,
                                              .NumControls = 2,
                                              .Control = {1, 6},
                                              .large_control = NULL,
                                              .GateValue = 1,
                                              .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L6[] = {{.Gate = X,
                                              .Target = 3,
                                              .NumControls = 2,
                                              .Control = {2, 7},
                                              .large_control = NULL,
                                              .GateValue = 1,
                                              .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L7[] = {{.Gate = X,
                                              .Target = 3,
                                              .NumControls = 2,
                                              .Control = {2, 7},
                                              .large_control = NULL,
                                              .GateValue = 1,
                                              .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L8[] = {{.Gate = X,
                                              .Target = 2,
                                              .NumControls = 1,
                                              .Control = {3},
                                              .large_control = NULL,
                                              .GateValue = 1,
                                              .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L9[] = {{.Gate = X,
                                              .Target = 7,
                                              .NumControls = 1,
                                              .Control = {2},
                                              .large_control = NULL,
                                              .GateValue = 1,
                                              .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L10[] = {{.Gate = X,
                                               .Target = 2,
                                               .NumControls = 2,
                                               .Control = {1, 6},
                                               .large_control = NULL,
                                               .GateValue = 1,
                                               .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L11[] = {{.Gate = X,
                                               .Target = 1,
                                               .NumControls = 1,
                                               .Control = {2},
                                               .large_control = NULL,
                                               .GateValue = 1,
                                               .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L12[] = {{.Gate = X,
                                               .Target = 6,
                                               .NumControls = 1,
                                               .Control = {1},
                                               .large_control = NULL,
                                               .GateValue = 1,
                                               .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L13[] = {{.Gate = X,
                                               .Target = 1,
                                               .NumControls = 2,
                                               .Control = {0, 5},
                                               .large_control = NULL,
                                               .GateValue = 1,
                                               .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L14[] = {{.Gate = X,
                                               .Target = 0,
                                               .NumControls = 1,
                                               .Control = {1},
                                               .large_control = NULL,
                                               .GateValue = 1,
                                               .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L15[] = {{.Gate = X,
                                               .Target = 5,
                                               .NumControls = 1,
                                               .Control = {0},
                                               .large_control = NULL,
                                               .GateValue = 1,
                                               .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L16[] = {{.Gate = X,
                                               .Target = 0,
                                               .NumControls = 2,
                                               .Control = {8, 4},
                                               .large_control = NULL,
                                               .GateValue = 1,
                                               .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L17[] = {{.Gate = X,
                                               .Target = 8,
                                               .NumControls = 1,
                                               .Control = {0},
                                               .large_control = NULL,
                                               .GateValue = 1,
                                               .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L18[] = {{.Gate = X,
                                               .Target = 4,
                                               .NumControls = 1,
                                               .Control = {8},
                                               .large_control = NULL,
                                               .GateValue = 1,
                                               .NumBasisGates = 0}};

static const gate_t TOFFOLI_CQ_INC_4_L19[] = {{.Gate = X,
                                               .Target = 0,
                                               .NumControls = 0,
                                               .Control = {0},
                                               .large_control = NULL,
                                               .GateValue = 1,
                                               .NumBasisGates = 0}};

static const gate_t *TOFFOLI_CQ_INC_4_LAYERS[] = {
    TOFFOLI_CQ_INC_4_L0,  TOFFOLI_CQ_INC_4_L1,  TOFFOLI_CQ_INC_4_L2,  TOFFOLI_CQ_INC_4_L3,
    TOFFOLI_CQ_INC_4_L4,  TOFFOLI_CQ_INC_4_L5,  TOFFOLI_CQ_INC_4_L6,  TOFFOLI_CQ_INC_4_L7,
    TOFFOLI_CQ_INC_4_L8,  TOFFOLI_CQ_INC_4_L9,  TOFFOLI_CQ_INC_4_L10, TOFFOLI_CQ_INC_4_L11,
    TOFFOLI_CQ_INC_4_L12, TOFFOLI_CQ_INC_4_L13, TOFFOLI_CQ_INC_4_L14, TOFFOLI_CQ_INC_4_L15,
    TOFFOLI_CQ_INC_4_L16, TOFFOLI_CQ_INC_4_L17, TOFFOLI_CQ_INC_4_L18, TOFFOLI_CQ_INC_4_L19};
static const num_t TOFFOLI_CQ_INC_4_GPL[] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                             1, 1, 1, 1, 1, 1, 1, 1, 1, 1};

static const sequence_t HARDCODED_TOFFOLI_CQ_INC_4 = {.seq = (gate_t **)TOFFOLI_CQ_INC_4_LAYERS,
                                                      .num_layer = 20,
                                                      .used_layer = 20,
                                                      .gates_per_layer =
                                                          (num_t *)TOFFOLI_CQ_INC_4_GPL};

// ============================================================================
// TOFFOLI cCQ_INC WIDTH 4 (20 layers)
// Qubit layout: [0..3] = temp, [4..7] = self, [8] = carry, [9] = ext_ctrl
// Total qubits: 10
// ============================================================================

static sequence_t *cached_toffoli_cCQ_inc_4 = NULL;

static sequence_t *init_toffoli_cCQ_inc_4(void) {
    if (cached_toffoli_cCQ_inc_4 != NULL)
        return cached_toffoli_cCQ_inc_4;

    sequence_t *seq = malloc(sizeof(sequence_t));
    if (seq == NULL)
        return NULL;
    seq->num_layer = 20;
    seq->used_layer = 20;
    seq->gates_per_layer = calloc(20, sizeof(num_t));
    seq->seq = calloc(20, sizeof(gate_t *));
    if (seq->gates_per_layer == NULL || seq->seq == NULL) {
        free(seq->gates_per_layer);
        free(seq->seq);
        free(seq);
        return NULL;
    }

    // Layer 0: CX(target=0, ctrl=9)
    seq->gates_per_layer[0] = 1;
    seq->seq[0] = calloc(1, sizeof(gate_t));
    if (seq->seq[0] == NULL)
        goto cleanup;
    seq->seq[0][0] = (gate_t){.Gate = X,
                              .Target = 0,
                              .NumControls = 1,
                              .Control = {9},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 1: CCX(target=4, ctrl1=0, ctrl2=9)
    seq->gates_per_layer[1] = 1;
    seq->seq[1] = calloc(1, sizeof(gate_t));
    if (seq->seq[1] == NULL)
        goto cleanup;
    seq->seq[1][0] = (gate_t){.Gate = X,
                              .Target = 4,
                              .NumControls = 2,
                              .Control = {0, 9},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 2: CCX(target=8, ctrl1=0, ctrl2=9)
    seq->gates_per_layer[2] = 1;
    seq->seq[2] = calloc(1, sizeof(gate_t));
    if (seq->seq[2] == NULL)
        goto cleanup;
    seq->seq[2][0] = (gate_t){.Gate = X,
                              .Target = 8,
                              .NumControls = 2,
                              .Control = {0, 9},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 3: MCX(target=0, ctrls=[8, 4, 9])
    seq->gates_per_layer[3] = 1;
    seq->seq[3] = calloc(1, sizeof(gate_t));
    if (seq->seq[3] == NULL)
        goto cleanup;
    seq->seq[3][0].Gate = X;
    seq->seq[3][0].Target = 0;
    seq->seq[3][0].NumControls = 3;
    seq->seq[3][0].Control[0] = 8;
    seq->seq[3][0].Control[1] = 4;
    seq->seq[3][0].GateValue = 1;
    seq->seq[3][0].NumBasisGates = 0;
    seq->seq[3][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[3][0].large_control[0] = (qubit_t)8;
    seq->seq[3][0].large_control[1] = (qubit_t)4;
    seq->seq[3][0].large_control[2] = (qubit_t)9;

    // Layer 4: MCX(target=1, ctrls=[0, 5, 9])
    seq->gates_per_layer[4] = 1;
    seq->seq[4] = calloc(1, sizeof(gate_t));
    if (seq->seq[4] == NULL)
        goto cleanup;
    seq->seq[4][0].Gate = X;
    seq->seq[4][0].Target = 1;
    seq->seq[4][0].NumControls = 3;
    seq->seq[4][0].Control[0] = 0;
    seq->seq[4][0].Control[1] = 5;
    seq->seq[4][0].GateValue = 1;
    seq->seq[4][0].NumBasisGates = 0;
    seq->seq[4][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[4][0].large_control[0] = (qubit_t)0;
    seq->seq[4][0].large_control[1] = (qubit_t)5;
    seq->seq[4][0].large_control[2] = (qubit_t)9;

    // Layer 5: MCX(target=2, ctrls=[1, 6, 9])
    seq->gates_per_layer[5] = 1;
    seq->seq[5] = calloc(1, sizeof(gate_t));
    if (seq->seq[5] == NULL)
        goto cleanup;
    seq->seq[5][0].Gate = X;
    seq->seq[5][0].Target = 2;
    seq->seq[5][0].NumControls = 3;
    seq->seq[5][0].Control[0] = 1;
    seq->seq[5][0].Control[1] = 6;
    seq->seq[5][0].GateValue = 1;
    seq->seq[5][0].NumBasisGates = 0;
    seq->seq[5][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[5][0].large_control[0] = (qubit_t)1;
    seq->seq[5][0].large_control[1] = (qubit_t)6;
    seq->seq[5][0].large_control[2] = (qubit_t)9;

    // Layer 6: MCX(target=3, ctrls=[2, 7, 9])
    seq->gates_per_layer[6] = 1;
    seq->seq[6] = calloc(1, sizeof(gate_t));
    if (seq->seq[6] == NULL)
        goto cleanup;
    seq->seq[6][0].Gate = X;
    seq->seq[6][0].Target = 3;
    seq->seq[6][0].NumControls = 3;
    seq->seq[6][0].Control[0] = 2;
    seq->seq[6][0].Control[1] = 7;
    seq->seq[6][0].GateValue = 1;
    seq->seq[6][0].NumBasisGates = 0;
    seq->seq[6][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[6][0].large_control[0] = (qubit_t)2;
    seq->seq[6][0].large_control[1] = (qubit_t)7;
    seq->seq[6][0].large_control[2] = (qubit_t)9;

    // Layer 7: MCX(target=3, ctrls=[2, 7, 9])
    seq->gates_per_layer[7] = 1;
    seq->seq[7] = calloc(1, sizeof(gate_t));
    if (seq->seq[7] == NULL)
        goto cleanup;
    seq->seq[7][0].Gate = X;
    seq->seq[7][0].Target = 3;
    seq->seq[7][0].NumControls = 3;
    seq->seq[7][0].Control[0] = 2;
    seq->seq[7][0].Control[1] = 7;
    seq->seq[7][0].GateValue = 1;
    seq->seq[7][0].NumBasisGates = 0;
    seq->seq[7][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[7][0].large_control[0] = (qubit_t)2;
    seq->seq[7][0].large_control[1] = (qubit_t)7;
    seq->seq[7][0].large_control[2] = (qubit_t)9;

    // Layer 8: CCX(target=2, ctrl1=3, ctrl2=9)
    seq->gates_per_layer[8] = 1;
    seq->seq[8] = calloc(1, sizeof(gate_t));
    if (seq->seq[8] == NULL)
        goto cleanup;
    seq->seq[8][0] = (gate_t){.Gate = X,
                              .Target = 2,
                              .NumControls = 2,
                              .Control = {3, 9},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 9: CCX(target=7, ctrl1=2, ctrl2=9)
    seq->gates_per_layer[9] = 1;
    seq->seq[9] = calloc(1, sizeof(gate_t));
    if (seq->seq[9] == NULL)
        goto cleanup;
    seq->seq[9][0] = (gate_t){.Gate = X,
                              .Target = 7,
                              .NumControls = 2,
                              .Control = {2, 9},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 10: MCX(target=2, ctrls=[1, 6, 9])
    seq->gates_per_layer[10] = 1;
    seq->seq[10] = calloc(1, sizeof(gate_t));
    if (seq->seq[10] == NULL)
        goto cleanup;
    seq->seq[10][0].Gate = X;
    seq->seq[10][0].Target = 2;
    seq->seq[10][0].NumControls = 3;
    seq->seq[10][0].Control[0] = 1;
    seq->seq[10][0].Control[1] = 6;
    seq->seq[10][0].GateValue = 1;
    seq->seq[10][0].NumBasisGates = 0;
    seq->seq[10][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[10][0].large_control[0] = (qubit_t)1;
    seq->seq[10][0].large_control[1] = (qubit_t)6;
    seq->seq[10][0].large_control[2] = (qubit_t)9;

    // Layer 11: CCX(target=1, ctrl1=2, ctrl2=9)
    seq->gates_per_layer[11] = 1;
    seq->seq[11] = calloc(1, sizeof(gate_t));
    if (seq->seq[11] == NULL)
        goto cleanup;
    seq->seq[11][0] = (gate_t){.Gate = X,
                               .Target = 1,
                               .NumControls = 2,
                               .Control = {2, 9},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 12: CCX(target=6, ctrl1=1, ctrl2=9)
    seq->gates_per_layer[12] = 1;
    seq->seq[12] = calloc(1, sizeof(gate_t));
    if (seq->seq[12] == NULL)
        goto cleanup;
    seq->seq[12][0] = (gate_t){.Gate = X,
                               .Target = 6,
                               .NumControls = 2,
                               .Control = {1, 9},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 13: MCX(target=1, ctrls=[0, 5, 9])
    seq->gates_per_layer[13] = 1;
    seq->seq[13] = calloc(1, sizeof(gate_t));
    if (seq->seq[13] == NULL)
        goto cleanup;
    seq->seq[13][0].Gate = X;
    seq->seq[13][0].Target = 1;
    seq->seq[13][0].NumControls = 3;
    seq->seq[13][0].Control[0] = 0;
    seq->seq[13][0].Control[1] = 5;
    seq->seq[13][0].GateValue = 1;
    seq->seq[13][0].NumBasisGates = 0;
    seq->seq[13][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[13][0].large_control[0] = (qubit_t)0;
    seq->seq[13][0].large_control[1] = (qubit_t)5;
    seq->seq[13][0].large_control[2] = (qubit_t)9;

    // Layer 14: CCX(target=0, ctrl1=1, ctrl2=9)
    seq->gates_per_layer[14] = 1;
    seq->seq[14] = calloc(1, sizeof(gate_t));
    if (seq->seq[14] == NULL)
        goto cleanup;
    seq->seq[14][0] = (gate_t){.Gate = X,
                               .Target = 0,
                               .NumControls = 2,
                               .Control = {1, 9},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 15: CCX(target=5, ctrl1=0, ctrl2=9)
    seq->gates_per_layer[15] = 1;
    seq->seq[15] = calloc(1, sizeof(gate_t));
    if (seq->seq[15] == NULL)
        goto cleanup;
    seq->seq[15][0] = (gate_t){.Gate = X,
                               .Target = 5,
                               .NumControls = 2,
                               .Control = {0, 9},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 16: MCX(target=0, ctrls=[8, 4, 9])
    seq->gates_per_layer[16] = 1;
    seq->seq[16] = calloc(1, sizeof(gate_t));
    if (seq->seq[16] == NULL)
        goto cleanup;
    seq->seq[16][0].Gate = X;
    seq->seq[16][0].Target = 0;
    seq->seq[16][0].NumControls = 3;
    seq->seq[16][0].Control[0] = 8;
    seq->seq[16][0].Control[1] = 4;
    seq->seq[16][0].GateValue = 1;
    seq->seq[16][0].NumBasisGates = 0;
    seq->seq[16][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[16][0].large_control[0] = (qubit_t)8;
    seq->seq[16][0].large_control[1] = (qubit_t)4;
    seq->seq[16][0].large_control[2] = (qubit_t)9;

    // Layer 17: CCX(target=8, ctrl1=0, ctrl2=9)
    seq->gates_per_layer[17] = 1;
    seq->seq[17] = calloc(1, sizeof(gate_t));
    if (seq->seq[17] == NULL)
        goto cleanup;
    seq->seq[17][0] = (gate_t){.Gate = X,
                               .Target = 8,
                               .NumControls = 2,
                               .Control = {0, 9},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 18: CCX(target=4, ctrl1=8, ctrl2=9)
    seq->gates_per_layer[18] = 1;
    seq->seq[18] = calloc(1, sizeof(gate_t));
    if (seq->seq[18] == NULL)
        goto cleanup;
    seq->seq[18][0] = (gate_t){.Gate = X,
                               .Target = 4,
                               .NumControls = 2,
                               .Control = {8, 9},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 19: CX(target=0, ctrl=9)
    seq->gates_per_layer[19] = 1;
    seq->seq[19] = calloc(1, sizeof(gate_t));
    if (seq->seq[19] == NULL)
        goto cleanup;
    seq->seq[19][0] = (gate_t){.Gate = X,
                               .Target = 0,
                               .NumControls = 1,
                               .Control = {9},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    cached_toffoli_cCQ_inc_4 = seq;
    return seq;

cleanup:
    for (int i = 0; i < 20; i++) {
        if (seq->seq[i] != NULL) {
            if (seq->seq[i][0].large_control != NULL)
                free(seq->seq[i][0].large_control);
            free(seq->seq[i]);
        }
    }
    free(seq->seq);
    free(seq->gates_per_layer);
    free(seq);
    return NULL;
}

// ============================================================================
// DISPATCH HELPERS FOR WIDTH 4
// ============================================================================

const sequence_t *get_hardcoded_toffoli_CQ_inc_4(int bits) {
    (void)bits;
    return &HARDCODED_TOFFOLI_CQ_INC_4;
}

const sequence_t *get_hardcoded_toffoli_cCQ_inc_4(int bits) {
    (void)bits;
    return (const sequence_t *)init_toffoli_cCQ_inc_4();
}

#endif // TOFFOLI_SEQ_WIDTH_4
