//
// toffoli_add_seq_1.c - Hardcoded Toffoli addition sequences for 1-bit width
//
// Generated by scripts/generate_toffoli_seq.py - DO NOT EDIT MANUALLY
//
// Contains: Toffoli QQ_add (static const), cQQ_add (dynamic init, cached)
// Algorithm: CDKM ripple-carry adder (Cuccaro et al., 2004)
//

#include "toffoli_sequences.h"

#ifdef TOFFOLI_SEQ_WIDTH_1

#include <stdlib.h>

// ============================================================================
// TOFFOLI QQ_ADD WIDTH 1 (1 layers)
// Qubit layout: [0] = target, [1] = source
// Total qubits: 2
// ============================================================================

static const gate_t TOFFOLI_QQ_1_L0[] = {{.Gate = X,
                                          .Target = 0,
                                          .NumControls = 1,
                                          .Control = {1},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t *TOFFOLI_QQ_1_LAYERS[] = {TOFFOLI_QQ_1_L0};
static const num_t TOFFOLI_QQ_1_GPL[] = {1};

static const sequence_t HARDCODED_TOFFOLI_QQ_1 = {.seq = (gate_t **)TOFFOLI_QQ_1_LAYERS,
                                                  .num_layer = 1,
                                                  .used_layer = 1,
                                                  .gates_per_layer = (num_t *)TOFFOLI_QQ_1_GPL};

// ============================================================================
// TOFFOLI cQQ_ADD WIDTH 1 (1 layers)
// Qubit layout: [0] = target, [1] = source, [2] = ext_ctrl
// Total qubits: 3
// ============================================================================

static sequence_t *cached_toffoli_cQQ_1 = NULL;

static sequence_t *init_toffoli_cQQ_1(void) {
    if (cached_toffoli_cQQ_1 != NULL)
        return cached_toffoli_cQQ_1;

    sequence_t *seq = malloc(sizeof(sequence_t));
    if (seq == NULL)
        return NULL;
    seq->num_layer = 1;
    seq->used_layer = 1;
    seq->gates_per_layer = calloc(1, sizeof(num_t));
    seq->seq = calloc(1, sizeof(gate_t *));
    if (seq->gates_per_layer == NULL || seq->seq == NULL) {
        free(seq->gates_per_layer);
        free(seq->seq);
        free(seq);
        return NULL;
    }

    // Layer 0: CCX(target=0, ctrl1=1, ctrl2=2)
    seq->gates_per_layer[0] = 1;
    seq->seq[0] = calloc(1, sizeof(gate_t));
    if (seq->seq[0] == NULL)
        goto cleanup;
    seq->seq[0][0] = (gate_t){.Gate = X,
                              .Target = 0,
                              .NumControls = 2,
                              .Control = {1, 2},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    cached_toffoli_cQQ_1 = seq;
    return seq;

cleanup:
    for (int i = 0; i < 1; i++) {
        if (seq->seq[i] != NULL) {
            if (seq->seq[i][0].large_control != NULL)
                free(seq->seq[i][0].large_control);
            free(seq->seq[i]);
        }
    }
    free(seq->seq);
    free(seq->gates_per_layer);
    free(seq);
    return NULL;
}

// ============================================================================
// DISPATCH HELPERS FOR WIDTH 1
// ============================================================================

const sequence_t *get_hardcoded_toffoli_QQ_add_1(int bits) {
    (void)bits;
    return &HARDCODED_TOFFOLI_QQ_1;
}

const sequence_t *get_hardcoded_toffoli_cQQ_add_1(int bits) {
    (void)bits;
    return (const sequence_t *)init_toffoli_cQQ_1();
}

#endif // TOFFOLI_SEQ_WIDTH_1
