//
// toffoli_add_seq_2.c - Hardcoded Toffoli addition sequences for 2-bit width
//
// Generated by scripts/generate_toffoli_seq.py - DO NOT EDIT MANUALLY
//
// Contains: Toffoli QQ_add (static const), cQQ_add (dynamic init, cached)
// Algorithm: CDKM ripple-carry adder (Cuccaro et al., 2004)
//

#include "toffoli_sequences.h"

#ifdef TOFFOLI_SEQ_WIDTH_2

#include <stdlib.h>

// ============================================================================
// TOFFOLI QQ_ADD WIDTH 2 (12 layers)
// Qubit layout: [0,1] = target (a), [2,3] = source (b), [4] = ancilla
// Total qubits: 5
// ============================================================================

static const gate_t TOFFOLI_QQ_2_L0[] = {{.Gate = X,
                                          .Target = 2,
                                          .NumControls = 1,
                                          .Control = {0},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_2_L1[] = {{.Gate = X,
                                          .Target = 4,
                                          .NumControls = 1,
                                          .Control = {0},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_2_L2[] = {{.Gate = X,
                                          .Target = 0,
                                          .NumControls = 2,
                                          .Control = {4, 2},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_2_L3[] = {{.Gate = X,
                                          .Target = 3,
                                          .NumControls = 1,
                                          .Control = {1},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_2_L4[] = {{.Gate = X,
                                          .Target = 0,
                                          .NumControls = 1,
                                          .Control = {1},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_2_L5[] = {{.Gate = X,
                                          .Target = 1,
                                          .NumControls = 2,
                                          .Control = {0, 3},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_2_L6[] = {{.Gate = X,
                                          .Target = 1,
                                          .NumControls = 2,
                                          .Control = {0, 3},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_2_L7[] = {{.Gate = X,
                                          .Target = 0,
                                          .NumControls = 1,
                                          .Control = {1},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_2_L8[] = {{.Gate = X,
                                          .Target = 3,
                                          .NumControls = 1,
                                          .Control = {0},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_2_L9[] = {{.Gate = X,
                                          .Target = 0,
                                          .NumControls = 2,
                                          .Control = {4, 2},
                                          .large_control = NULL,
                                          .GateValue = 1,
                                          .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_2_L10[] = {{.Gate = X,
                                           .Target = 4,
                                           .NumControls = 1,
                                           .Control = {0},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t TOFFOLI_QQ_2_L11[] = {{.Gate = X,
                                           .Target = 2,
                                           .NumControls = 1,
                                           .Control = {4},
                                           .large_control = NULL,
                                           .GateValue = 1,
                                           .NumBasisGates = 0}};

static const gate_t *TOFFOLI_QQ_2_LAYERS[] = {TOFFOLI_QQ_2_L0, TOFFOLI_QQ_2_L1,  TOFFOLI_QQ_2_L2,
                                              TOFFOLI_QQ_2_L3, TOFFOLI_QQ_2_L4,  TOFFOLI_QQ_2_L5,
                                              TOFFOLI_QQ_2_L6, TOFFOLI_QQ_2_L7,  TOFFOLI_QQ_2_L8,
                                              TOFFOLI_QQ_2_L9, TOFFOLI_QQ_2_L10, TOFFOLI_QQ_2_L11};
static const num_t TOFFOLI_QQ_2_GPL[] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};

static const sequence_t HARDCODED_TOFFOLI_QQ_2 = {.seq = (gate_t **)TOFFOLI_QQ_2_LAYERS,
                                                  .num_layer = 12,
                                                  .used_layer = 12,
                                                  .gates_per_layer = (num_t *)TOFFOLI_QQ_2_GPL};

// ============================================================================
// TOFFOLI cQQ_ADD WIDTH 2 (12 layers)
// Qubit layout: [0,1] = target (a), [2,3] = source (b), [4] = ancilla, [5] = ext_ctrl
// Total qubits: 6
// ============================================================================

static sequence_t *cached_toffoli_cQQ_2 = NULL;

static sequence_t *init_toffoli_cQQ_2(void) {
    if (cached_toffoli_cQQ_2 != NULL)
        return cached_toffoli_cQQ_2;

    sequence_t *seq = malloc(sizeof(sequence_t));
    if (seq == NULL)
        return NULL;
    seq->num_layer = 12;
    seq->used_layer = 12;
    seq->gates_per_layer = calloc(12, sizeof(num_t));
    seq->seq = calloc(12, sizeof(gate_t *));
    if (seq->gates_per_layer == NULL || seq->seq == NULL) {
        free(seq->gates_per_layer);
        free(seq->seq);
        free(seq);
        return NULL;
    }

    // Layer 0: CCX(target=2, ctrl1=0, ctrl2=5)
    seq->gates_per_layer[0] = 1;
    seq->seq[0] = calloc(1, sizeof(gate_t));
    if (seq->seq[0] == NULL)
        goto cleanup;
    seq->seq[0][0] = (gate_t){.Gate = X,
                              .Target = 2,
                              .NumControls = 2,
                              .Control = {0, 5},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 1: CCX(target=4, ctrl1=0, ctrl2=5)
    seq->gates_per_layer[1] = 1;
    seq->seq[1] = calloc(1, sizeof(gate_t));
    if (seq->seq[1] == NULL)
        goto cleanup;
    seq->seq[1][0] = (gate_t){.Gate = X,
                              .Target = 4,
                              .NumControls = 2,
                              .Control = {0, 5},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 2: MCX(target=0, ctrls=[4,2,5])
    seq->gates_per_layer[2] = 1;
    seq->seq[2] = calloc(1, sizeof(gate_t));
    if (seq->seq[2] == NULL)
        goto cleanup;
    seq->seq[2][0].Gate = X;
    seq->seq[2][0].Target = 0;
    seq->seq[2][0].NumControls = 3;
    seq->seq[2][0].Control[0] = 4;
    seq->seq[2][0].Control[1] = 2;
    seq->seq[2][0].GateValue = 1;
    seq->seq[2][0].NumBasisGates = 0;
    seq->seq[2][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[2][0].large_control[0] = (qubit_t)4;
    seq->seq[2][0].large_control[1] = (qubit_t)2;
    seq->seq[2][0].large_control[2] = (qubit_t)5;

    // Layer 3: CCX(target=3, ctrl1=1, ctrl2=5)
    seq->gates_per_layer[3] = 1;
    seq->seq[3] = calloc(1, sizeof(gate_t));
    if (seq->seq[3] == NULL)
        goto cleanup;
    seq->seq[3][0] = (gate_t){.Gate = X,
                              .Target = 3,
                              .NumControls = 2,
                              .Control = {1, 5},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 4: CCX(target=0, ctrl1=1, ctrl2=5)
    seq->gates_per_layer[4] = 1;
    seq->seq[4] = calloc(1, sizeof(gate_t));
    if (seq->seq[4] == NULL)
        goto cleanup;
    seq->seq[4][0] = (gate_t){.Gate = X,
                              .Target = 0,
                              .NumControls = 2,
                              .Control = {1, 5},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 5: MCX(target=1, ctrls=[0,3,5])
    seq->gates_per_layer[5] = 1;
    seq->seq[5] = calloc(1, sizeof(gate_t));
    if (seq->seq[5] == NULL)
        goto cleanup;
    seq->seq[5][0].Gate = X;
    seq->seq[5][0].Target = 1;
    seq->seq[5][0].NumControls = 3;
    seq->seq[5][0].Control[0] = 0;
    seq->seq[5][0].Control[1] = 3;
    seq->seq[5][0].GateValue = 1;
    seq->seq[5][0].NumBasisGates = 0;
    seq->seq[5][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[5][0].large_control[0] = (qubit_t)0;
    seq->seq[5][0].large_control[1] = (qubit_t)3;
    seq->seq[5][0].large_control[2] = (qubit_t)5;

    // Layer 6: MCX(target=1, ctrls=[0,3,5])
    seq->gates_per_layer[6] = 1;
    seq->seq[6] = calloc(1, sizeof(gate_t));
    if (seq->seq[6] == NULL)
        goto cleanup;
    seq->seq[6][0].Gate = X;
    seq->seq[6][0].Target = 1;
    seq->seq[6][0].NumControls = 3;
    seq->seq[6][0].Control[0] = 0;
    seq->seq[6][0].Control[1] = 3;
    seq->seq[6][0].GateValue = 1;
    seq->seq[6][0].NumBasisGates = 0;
    seq->seq[6][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[6][0].large_control[0] = (qubit_t)0;
    seq->seq[6][0].large_control[1] = (qubit_t)3;
    seq->seq[6][0].large_control[2] = (qubit_t)5;

    // Layer 7: CCX(target=0, ctrl1=1, ctrl2=5)
    seq->gates_per_layer[7] = 1;
    seq->seq[7] = calloc(1, sizeof(gate_t));
    if (seq->seq[7] == NULL)
        goto cleanup;
    seq->seq[7][0] = (gate_t){.Gate = X,
                              .Target = 0,
                              .NumControls = 2,
                              .Control = {1, 5},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 8: CCX(target=3, ctrl1=0, ctrl2=5)
    seq->gates_per_layer[8] = 1;
    seq->seq[8] = calloc(1, sizeof(gate_t));
    if (seq->seq[8] == NULL)
        goto cleanup;
    seq->seq[8][0] = (gate_t){.Gate = X,
                              .Target = 3,
                              .NumControls = 2,
                              .Control = {0, 5},
                              .large_control = NULL,
                              .GateValue = 1,
                              .NumBasisGates = 0};

    // Layer 9: MCX(target=0, ctrls=[4,2,5])
    seq->gates_per_layer[9] = 1;
    seq->seq[9] = calloc(1, sizeof(gate_t));
    if (seq->seq[9] == NULL)
        goto cleanup;
    seq->seq[9][0].Gate = X;
    seq->seq[9][0].Target = 0;
    seq->seq[9][0].NumControls = 3;
    seq->seq[9][0].Control[0] = 4;
    seq->seq[9][0].Control[1] = 2;
    seq->seq[9][0].GateValue = 1;
    seq->seq[9][0].NumBasisGates = 0;
    seq->seq[9][0].large_control = malloc(3 * sizeof(qubit_t));
    seq->seq[9][0].large_control[0] = (qubit_t)4;
    seq->seq[9][0].large_control[1] = (qubit_t)2;
    seq->seq[9][0].large_control[2] = (qubit_t)5;

    // Layer 10: CCX(target=4, ctrl1=0, ctrl2=5)
    seq->gates_per_layer[10] = 1;
    seq->seq[10] = calloc(1, sizeof(gate_t));
    if (seq->seq[10] == NULL)
        goto cleanup;
    seq->seq[10][0] = (gate_t){.Gate = X,
                               .Target = 4,
                               .NumControls = 2,
                               .Control = {0, 5},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    // Layer 11: CCX(target=2, ctrl1=4, ctrl2=5)
    seq->gates_per_layer[11] = 1;
    seq->seq[11] = calloc(1, sizeof(gate_t));
    if (seq->seq[11] == NULL)
        goto cleanup;
    seq->seq[11][0] = (gate_t){.Gate = X,
                               .Target = 2,
                               .NumControls = 2,
                               .Control = {4, 5},
                               .large_control = NULL,
                               .GateValue = 1,
                               .NumBasisGates = 0};

    cached_toffoli_cQQ_2 = seq;
    return seq;

cleanup:
    for (int i = 0; i < 12; i++) {
        if (seq->seq[i] != NULL) {
            if (seq->seq[i][0].large_control != NULL)
                free(seq->seq[i][0].large_control);
            free(seq->seq[i]);
        }
    }
    free(seq->seq);
    free(seq->gates_per_layer);
    free(seq);
    return NULL;
}

// ============================================================================
// DISPATCH HELPERS FOR WIDTH 2
// ============================================================================

const sequence_t *get_hardcoded_toffoli_QQ_add_2(int bits) {
    (void)bits;
    return &HARDCODED_TOFFOLI_QQ_2;
}

const sequence_t *get_hardcoded_toffoli_cQQ_add_2(int bits) {
    (void)bits;
    return (const sequence_t *)init_toffoli_cQQ_2();
}

#endif // TOFFOLI_SEQ_WIDTH_2
