//
// toffoli_clifft_cq_inc_1.c - CDKM CQ increment Clifford+T for 1-bit width
//
// Generated by scripts/generate_toffoli_clifft_cq_inc.py - DO NOT EDIT MANUALLY
//
// Contains: Toffoli CDKM CQ increment (value=1) Clifford+T (static const, zero CCX)
// Algorithm: CDKM ripple-carry adder with classical-bit simplification + CCX->Clifford+T
// All gates: H/T/Tdg/CX/X (max 1 control) -- fully static const.
//

#include "toffoli_sequences.h"

#ifdef TOFFOLI_SEQ_WIDTH_1

// ============================================================================
// TOFFOLI CLIFFT CQ_INC WIDTH 1 (1 layers)
// Qubit layout: [0] = self
// Total qubits: 1
// All gates: H/T/Tdg/CX/X (max 1 control) -- zero CCX
// ============================================================================

static const gate_t TOFFOLI_CLIFFT_CQ_INC_1_L0[] = {{.Gate = X,
                                                     .Target = 0,
                                                     .NumControls = 0,
                                                     .Control = {0},
                                                     .large_control = NULL,
                                                     .GateValue = 1,
                                                     .NumBasisGates = 0}};

static const gate_t *TOFFOLI_CLIFFT_CQ_INC_1_LAYERS[] = {TOFFOLI_CLIFFT_CQ_INC_1_L0};
static const num_t TOFFOLI_CLIFFT_CQ_INC_1_GPL[] = {1};

static const sequence_t HARDCODED_TOFFOLI_CLIFFT_CQ_INC_1 = {
    .seq = (gate_t **)TOFFOLI_CLIFFT_CQ_INC_1_LAYERS,
    .num_layer = 1,
    .used_layer = 1,
    .gates_per_layer = (num_t *)TOFFOLI_CLIFFT_CQ_INC_1_GPL};

// ============================================================================
// DISPATCH HELPER FOR WIDTH 1
// ============================================================================

const sequence_t *get_hardcoded_toffoli_clifft_CQ_inc_1(int bits) {
    (void)bits;
    return &HARDCODED_TOFFOLI_CLIFFT_CQ_INC_1;
}

#endif // TOFFOLI_SEQ_WIDTH_1
