//
// toffoli_clifft_cq_inc_5.c - CDKM CQ increment Clifford+T for 5-bit width
//
// Generated by scripts/generate_toffoli_clifft_cq_inc.py - DO NOT EDIT MANUALLY
//
// Contains: Toffoli CDKM CQ increment (value=1) Clifford+T (static const, zero CCX)
// Algorithm: CDKM ripple-carry adder with classical-bit simplification + CCX->Clifford+T
// All gates: H/T/Tdg/CX/X (max 1 control) -- fully static const.
//

#include "toffoli_sequences.h"

#ifdef TOFFOLI_SEQ_WIDTH_5

#include <math.h>

// ============================================================================
// TOFFOLI CLIFFT CQ_INC WIDTH 5 (164 layers)
// Qubit layout: [0,4] = temp, [5,9] = self, [10] = carry
// Total qubits: 11
// All gates: H/T/Tdg/CX/X (max 1 control) -- zero CCX
// ============================================================================

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L0[] = {{.Gate = X,
                                                     .Target = 0,
                                                     .NumControls = 0,
                                                     .Control = {0},
                                                     .large_control = NULL,
                                                     .GateValue = 1,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L1[] = {{.Gate = X,
                                                     .Target = 5,
                                                     .NumControls = 0,
                                                     .Control = {0},
                                                     .large_control = NULL,
                                                     .GateValue = 1,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L2[] = {{.Gate = X,
                                                     .Target = 10,
                                                     .NumControls = 0,
                                                     .Control = {0},
                                                     .large_control = NULL,
                                                     .GateValue = 1,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L3[] = {{.Gate = H,
                                                     .Target = 0,
                                                     .NumControls = 0,
                                                     .Control = {0},
                                                     .large_control = NULL,
                                                     .GateValue = 0,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L4[] = {{.Gate = X,
                                                     .Target = 0,
                                                     .NumControls = 1,
                                                     .Control = {5},
                                                     .large_control = NULL,
                                                     .GateValue = 1,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L5[] = {{.Gate = TDG_GATE,
                                                     .Target = 0,
                                                     .NumControls = 0,
                                                     .Control = {0},
                                                     .large_control = NULL,
                                                     .GateValue = -M_PI / 4.0,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L6[] = {{.Gate = X,
                                                     .Target = 0,
                                                     .NumControls = 1,
                                                     .Control = {10},
                                                     .large_control = NULL,
                                                     .GateValue = 1,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L7[] = {{.Gate = T_GATE,
                                                     .Target = 0,
                                                     .NumControls = 0,
                                                     .Control = {0},
                                                     .large_control = NULL,
                                                     .GateValue = M_PI / 4.0,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L8[] = {{.Gate = X,
                                                     .Target = 0,
                                                     .NumControls = 1,
                                                     .Control = {5},
                                                     .large_control = NULL,
                                                     .GateValue = 1,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L9[] = {{.Gate = TDG_GATE,
                                                     .Target = 0,
                                                     .NumControls = 0,
                                                     .Control = {0},
                                                     .large_control = NULL,
                                                     .GateValue = -M_PI / 4.0,
                                                     .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L10[] = {{.Gate = X,
                                                      .Target = 0,
                                                      .NumControls = 1,
                                                      .Control = {10},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L11[] = {{.Gate = T_GATE,
                                                      .Target = 0,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L12[] = {{.Gate = T_GATE,
                                                      .Target = 5,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L13[] = {{.Gate = H,
                                                      .Target = 0,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L14[] = {{.Gate = X,
                                                      .Target = 5,
                                                      .NumControls = 1,
                                                      .Control = {10},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L15[] = {{.Gate = T_GATE,
                                                      .Target = 10,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L16[] = {{.Gate = TDG_GATE,
                                                      .Target = 5,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L17[] = {{.Gate = X,
                                                      .Target = 5,
                                                      .NumControls = 1,
                                                      .Control = {10},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L18[] = {{.Gate = H,
                                                      .Target = 1,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L19[] = {{.Gate = X,
                                                      .Target = 1,
                                                      .NumControls = 1,
                                                      .Control = {6},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L20[] = {{.Gate = TDG_GATE,
                                                      .Target = 1,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L21[] = {{.Gate = X,
                                                      .Target = 1,
                                                      .NumControls = 1,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L22[] = {{.Gate = T_GATE,
                                                      .Target = 1,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L23[] = {{.Gate = X,
                                                      .Target = 1,
                                                      .NumControls = 1,
                                                      .Control = {6},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L24[] = {{.Gate = TDG_GATE,
                                                      .Target = 1,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L25[] = {{.Gate = X,
                                                      .Target = 1,
                                                      .NumControls = 1,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L26[] = {{.Gate = T_GATE,
                                                      .Target = 1,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L27[] = {{.Gate = T_GATE,
                                                      .Target = 6,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L28[] = {{.Gate = H,
                                                      .Target = 1,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L29[] = {{.Gate = X,
                                                      .Target = 6,
                                                      .NumControls = 1,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L30[] = {{.Gate = T_GATE,
                                                      .Target = 0,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L31[] = {{.Gate = TDG_GATE,
                                                      .Target = 6,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L32[] = {{.Gate = X,
                                                      .Target = 6,
                                                      .NumControls = 1,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L33[] = {{.Gate = H,
                                                      .Target = 2,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L34[] = {{.Gate = X,
                                                      .Target = 2,
                                                      .NumControls = 1,
                                                      .Control = {7},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L35[] = {{.Gate = TDG_GATE,
                                                      .Target = 2,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L36[] = {{.Gate = X,
                                                      .Target = 2,
                                                      .NumControls = 1,
                                                      .Control = {1},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L37[] = {{.Gate = T_GATE,
                                                      .Target = 2,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L38[] = {{.Gate = X,
                                                      .Target = 2,
                                                      .NumControls = 1,
                                                      .Control = {7},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L39[] = {{.Gate = TDG_GATE,
                                                      .Target = 2,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L40[] = {{.Gate = X,
                                                      .Target = 2,
                                                      .NumControls = 1,
                                                      .Control = {1},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L41[] = {{.Gate = T_GATE,
                                                      .Target = 2,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L42[] = {{.Gate = T_GATE,
                                                      .Target = 7,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L43[] = {{.Gate = H,
                                                      .Target = 2,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L44[] = {{.Gate = X,
                                                      .Target = 7,
                                                      .NumControls = 1,
                                                      .Control = {1},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L45[] = {{.Gate = T_GATE,
                                                      .Target = 1,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L46[] = {{.Gate = TDG_GATE,
                                                      .Target = 7,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L47[] = {{.Gate = X,
                                                      .Target = 7,
                                                      .NumControls = 1,
                                                      .Control = {1},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L48[] = {{.Gate = H,
                                                      .Target = 3,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L49[] = {{.Gate = X,
                                                      .Target = 3,
                                                      .NumControls = 1,
                                                      .Control = {8},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L50[] = {{.Gate = TDG_GATE,
                                                      .Target = 3,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L51[] = {{.Gate = X,
                                                      .Target = 3,
                                                      .NumControls = 1,
                                                      .Control = {2},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L52[] = {{.Gate = T_GATE,
                                                      .Target = 3,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L53[] = {{.Gate = X,
                                                      .Target = 3,
                                                      .NumControls = 1,
                                                      .Control = {8},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L54[] = {{.Gate = TDG_GATE,
                                                      .Target = 3,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L55[] = {{.Gate = X,
                                                      .Target = 3,
                                                      .NumControls = 1,
                                                      .Control = {2},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L56[] = {{.Gate = T_GATE,
                                                      .Target = 3,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L57[] = {{.Gate = T_GATE,
                                                      .Target = 8,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L58[] = {{.Gate = H,
                                                      .Target = 3,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L59[] = {{.Gate = X,
                                                      .Target = 8,
                                                      .NumControls = 1,
                                                      .Control = {2},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L60[] = {{.Gate = T_GATE,
                                                      .Target = 2,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L61[] = {{.Gate = TDG_GATE,
                                                      .Target = 8,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L62[] = {{.Gate = X,
                                                      .Target = 8,
                                                      .NumControls = 1,
                                                      .Control = {2},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L63[] = {{.Gate = H,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L64[] = {{.Gate = X,
                                                      .Target = 4,
                                                      .NumControls = 1,
                                                      .Control = {9},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L65[] = {{.Gate = TDG_GATE,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L66[] = {{.Gate = X,
                                                      .Target = 4,
                                                      .NumControls = 1,
                                                      .Control = {3},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L67[] = {{.Gate = T_GATE,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L68[] = {{.Gate = X,
                                                      .Target = 4,
                                                      .NumControls = 1,
                                                      .Control = {9},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L69[] = {{.Gate = TDG_GATE,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L70[] = {{.Gate = X,
                                                      .Target = 4,
                                                      .NumControls = 1,
                                                      .Control = {3},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L71[] = {{.Gate = T_GATE,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L72[] = {{.Gate = T_GATE,
                                                      .Target = 9,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L73[] = {{.Gate = H,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L74[] = {{.Gate = X,
                                                      .Target = 9,
                                                      .NumControls = 1,
                                                      .Control = {3},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L75[] = {{.Gate = T_GATE,
                                                      .Target = 3,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L76[] = {{.Gate = TDG_GATE,
                                                      .Target = 9,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L77[] = {{.Gate = X,
                                                      .Target = 9,
                                                      .NumControls = 1,
                                                      .Control = {3},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L78[] = {{.Gate = H,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L79[] = {{.Gate = X,
                                                      .Target = 4,
                                                      .NumControls = 1,
                                                      .Control = {9},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L80[] = {{.Gate = TDG_GATE,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L81[] = {{.Gate = X,
                                                      .Target = 4,
                                                      .NumControls = 1,
                                                      .Control = {3},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L82[] = {{.Gate = T_GATE,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L83[] = {{.Gate = X,
                                                      .Target = 4,
                                                      .NumControls = 1,
                                                      .Control = {9},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L84[] = {{.Gate = TDG_GATE,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L85[] = {{.Gate = X,
                                                      .Target = 4,
                                                      .NumControls = 1,
                                                      .Control = {3},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L86[] = {{.Gate = T_GATE,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L87[] = {{.Gate = T_GATE,
                                                      .Target = 9,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L88[] = {{.Gate = H,
                                                      .Target = 4,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L89[] = {{.Gate = X,
                                                      .Target = 9,
                                                      .NumControls = 1,
                                                      .Control = {3},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L90[] = {{.Gate = T_GATE,
                                                      .Target = 3,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L91[] = {{.Gate = TDG_GATE,
                                                      .Target = 9,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L92[] = {{.Gate = X,
                                                      .Target = 9,
                                                      .NumControls = 1,
                                                      .Control = {3},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L93[] = {{.Gate = X,
                                                      .Target = 3,
                                                      .NumControls = 1,
                                                      .Control = {4},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L94[] = {{.Gate = X,
                                                      .Target = 9,
                                                      .NumControls = 1,
                                                      .Control = {3},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L95[] = {{.Gate = H,
                                                      .Target = 3,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = 0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L96[] = {{.Gate = X,
                                                      .Target = 3,
                                                      .NumControls = 1,
                                                      .Control = {8},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L97[] = {{.Gate = TDG_GATE,
                                                      .Target = 3,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = -M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L98[] = {{.Gate = X,
                                                      .Target = 3,
                                                      .NumControls = 1,
                                                      .Control = {2},
                                                      .large_control = NULL,
                                                      .GateValue = 1,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L99[] = {{.Gate = T_GATE,
                                                      .Target = 3,
                                                      .NumControls = 0,
                                                      .Control = {0},
                                                      .large_control = NULL,
                                                      .GateValue = M_PI / 4.0,
                                                      .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L100[] = {{.Gate = X,
                                                       .Target = 3,
                                                       .NumControls = 1,
                                                       .Control = {8},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L101[] = {{.Gate = TDG_GATE,
                                                       .Target = 3,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = -M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L102[] = {{.Gate = X,
                                                       .Target = 3,
                                                       .NumControls = 1,
                                                       .Control = {2},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L103[] = {{.Gate = T_GATE,
                                                       .Target = 3,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L104[] = {{.Gate = T_GATE,
                                                       .Target = 8,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L105[] = {{.Gate = H,
                                                       .Target = 3,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = 0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L106[] = {{.Gate = X,
                                                       .Target = 8,
                                                       .NumControls = 1,
                                                       .Control = {2},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L107[] = {{.Gate = T_GATE,
                                                       .Target = 2,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L108[] = {{.Gate = TDG_GATE,
                                                       .Target = 8,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = -M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L109[] = {{.Gate = X,
                                                       .Target = 8,
                                                       .NumControls = 1,
                                                       .Control = {2},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L110[] = {{.Gate = X,
                                                       .Target = 2,
                                                       .NumControls = 1,
                                                       .Control = {3},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L111[] = {{.Gate = X,
                                                       .Target = 8,
                                                       .NumControls = 1,
                                                       .Control = {2},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L112[] = {{.Gate = H,
                                                       .Target = 2,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = 0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L113[] = {{.Gate = X,
                                                       .Target = 2,
                                                       .NumControls = 1,
                                                       .Control = {7},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L114[] = {{.Gate = TDG_GATE,
                                                       .Target = 2,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = -M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L115[] = {{.Gate = X,
                                                       .Target = 2,
                                                       .NumControls = 1,
                                                       .Control = {1},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L116[] = {{.Gate = T_GATE,
                                                       .Target = 2,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L117[] = {{.Gate = X,
                                                       .Target = 2,
                                                       .NumControls = 1,
                                                       .Control = {7},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L118[] = {{.Gate = TDG_GATE,
                                                       .Target = 2,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = -M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L119[] = {{.Gate = X,
                                                       .Target = 2,
                                                       .NumControls = 1,
                                                       .Control = {1},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L120[] = {{.Gate = T_GATE,
                                                       .Target = 2,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L121[] = {{.Gate = T_GATE,
                                                       .Target = 7,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L122[] = {{.Gate = H,
                                                       .Target = 2,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = 0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L123[] = {{.Gate = X,
                                                       .Target = 7,
                                                       .NumControls = 1,
                                                       .Control = {1},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L124[] = {{.Gate = T_GATE,
                                                       .Target = 1,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L125[] = {{.Gate = TDG_GATE,
                                                       .Target = 7,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = -M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L126[] = {{.Gate = X,
                                                       .Target = 7,
                                                       .NumControls = 1,
                                                       .Control = {1},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L127[] = {{.Gate = X,
                                                       .Target = 1,
                                                       .NumControls = 1,
                                                       .Control = {2},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L128[] = {{.Gate = X,
                                                       .Target = 7,
                                                       .NumControls = 1,
                                                       .Control = {1},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L129[] = {{.Gate = H,
                                                       .Target = 1,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = 0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L130[] = {{.Gate = X,
                                                       .Target = 1,
                                                       .NumControls = 1,
                                                       .Control = {6},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L131[] = {{.Gate = TDG_GATE,
                                                       .Target = 1,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = -M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L132[] = {{.Gate = X,
                                                       .Target = 1,
                                                       .NumControls = 1,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L133[] = {{.Gate = T_GATE,
                                                       .Target = 1,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L134[] = {{.Gate = X,
                                                       .Target = 1,
                                                       .NumControls = 1,
                                                       .Control = {6},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L135[] = {{.Gate = TDG_GATE,
                                                       .Target = 1,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = -M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L136[] = {{.Gate = X,
                                                       .Target = 1,
                                                       .NumControls = 1,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L137[] = {{.Gate = T_GATE,
                                                       .Target = 1,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L138[] = {{.Gate = T_GATE,
                                                       .Target = 6,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L139[] = {{.Gate = H,
                                                       .Target = 1,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = 0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L140[] = {{.Gate = X,
                                                       .Target = 6,
                                                       .NumControls = 1,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L141[] = {{.Gate = T_GATE,
                                                       .Target = 0,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L142[] = {{.Gate = TDG_GATE,
                                                       .Target = 6,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = -M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L143[] = {{.Gate = X,
                                                       .Target = 6,
                                                       .NumControls = 1,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L144[] = {{.Gate = X,
                                                       .Target = 0,
                                                       .NumControls = 1,
                                                       .Control = {1},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L145[] = {{.Gate = X,
                                                       .Target = 6,
                                                       .NumControls = 1,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L146[] = {{.Gate = H,
                                                       .Target = 0,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = 0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L147[] = {{.Gate = X,
                                                       .Target = 0,
                                                       .NumControls = 1,
                                                       .Control = {5},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L148[] = {{.Gate = TDG_GATE,
                                                       .Target = 0,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = -M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L149[] = {{.Gate = X,
                                                       .Target = 0,
                                                       .NumControls = 1,
                                                       .Control = {10},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L150[] = {{.Gate = T_GATE,
                                                       .Target = 0,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L151[] = {{.Gate = X,
                                                       .Target = 0,
                                                       .NumControls = 1,
                                                       .Control = {5},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L152[] = {{.Gate = TDG_GATE,
                                                       .Target = 0,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = -M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L153[] = {{.Gate = X,
                                                       .Target = 0,
                                                       .NumControls = 1,
                                                       .Control = {10},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L154[] = {{.Gate = T_GATE,
                                                       .Target = 0,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L155[] = {{.Gate = T_GATE,
                                                       .Target = 5,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L156[] = {{.Gate = H,
                                                       .Target = 0,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = 0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L157[] = {{.Gate = X,
                                                       .Target = 5,
                                                       .NumControls = 1,
                                                       .Control = {10},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L158[] = {{.Gate = T_GATE,
                                                       .Target = 10,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L159[] = {{.Gate = TDG_GATE,
                                                       .Target = 5,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = -M_PI / 4.0,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L160[] = {{.Gate = X,
                                                       .Target = 5,
                                                       .NumControls = 1,
                                                       .Control = {10},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L161[] = {{.Gate = X,
                                                       .Target = 10,
                                                       .NumControls = 1,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L162[] = {{.Gate = X,
                                                       .Target = 5,
                                                       .NumControls = 1,
                                                       .Control = {10},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t TOFFOLI_CLIFFT_CQ_INC_5_L163[] = {{.Gate = X,
                                                       .Target = 0,
                                                       .NumControls = 0,
                                                       .Control = {0},
                                                       .large_control = NULL,
                                                       .GateValue = 1,
                                                       .NumBasisGates = 0}};

static const gate_t *TOFFOLI_CLIFFT_CQ_INC_5_LAYERS[] = {
    TOFFOLI_CLIFFT_CQ_INC_5_L0,   TOFFOLI_CLIFFT_CQ_INC_5_L1,   TOFFOLI_CLIFFT_CQ_INC_5_L2,
    TOFFOLI_CLIFFT_CQ_INC_5_L3,   TOFFOLI_CLIFFT_CQ_INC_5_L4,   TOFFOLI_CLIFFT_CQ_INC_5_L5,
    TOFFOLI_CLIFFT_CQ_INC_5_L6,   TOFFOLI_CLIFFT_CQ_INC_5_L7,   TOFFOLI_CLIFFT_CQ_INC_5_L8,
    TOFFOLI_CLIFFT_CQ_INC_5_L9,   TOFFOLI_CLIFFT_CQ_INC_5_L10,  TOFFOLI_CLIFFT_CQ_INC_5_L11,
    TOFFOLI_CLIFFT_CQ_INC_5_L12,  TOFFOLI_CLIFFT_CQ_INC_5_L13,  TOFFOLI_CLIFFT_CQ_INC_5_L14,
    TOFFOLI_CLIFFT_CQ_INC_5_L15,  TOFFOLI_CLIFFT_CQ_INC_5_L16,  TOFFOLI_CLIFFT_CQ_INC_5_L17,
    TOFFOLI_CLIFFT_CQ_INC_5_L18,  TOFFOLI_CLIFFT_CQ_INC_5_L19,  TOFFOLI_CLIFFT_CQ_INC_5_L20,
    TOFFOLI_CLIFFT_CQ_INC_5_L21,  TOFFOLI_CLIFFT_CQ_INC_5_L22,  TOFFOLI_CLIFFT_CQ_INC_5_L23,
    TOFFOLI_CLIFFT_CQ_INC_5_L24,  TOFFOLI_CLIFFT_CQ_INC_5_L25,  TOFFOLI_CLIFFT_CQ_INC_5_L26,
    TOFFOLI_CLIFFT_CQ_INC_5_L27,  TOFFOLI_CLIFFT_CQ_INC_5_L28,  TOFFOLI_CLIFFT_CQ_INC_5_L29,
    TOFFOLI_CLIFFT_CQ_INC_5_L30,  TOFFOLI_CLIFFT_CQ_INC_5_L31,  TOFFOLI_CLIFFT_CQ_INC_5_L32,
    TOFFOLI_CLIFFT_CQ_INC_5_L33,  TOFFOLI_CLIFFT_CQ_INC_5_L34,  TOFFOLI_CLIFFT_CQ_INC_5_L35,
    TOFFOLI_CLIFFT_CQ_INC_5_L36,  TOFFOLI_CLIFFT_CQ_INC_5_L37,  TOFFOLI_CLIFFT_CQ_INC_5_L38,
    TOFFOLI_CLIFFT_CQ_INC_5_L39,  TOFFOLI_CLIFFT_CQ_INC_5_L40,  TOFFOLI_CLIFFT_CQ_INC_5_L41,
    TOFFOLI_CLIFFT_CQ_INC_5_L42,  TOFFOLI_CLIFFT_CQ_INC_5_L43,  TOFFOLI_CLIFFT_CQ_INC_5_L44,
    TOFFOLI_CLIFFT_CQ_INC_5_L45,  TOFFOLI_CLIFFT_CQ_INC_5_L46,  TOFFOLI_CLIFFT_CQ_INC_5_L47,
    TOFFOLI_CLIFFT_CQ_INC_5_L48,  TOFFOLI_CLIFFT_CQ_INC_5_L49,  TOFFOLI_CLIFFT_CQ_INC_5_L50,
    TOFFOLI_CLIFFT_CQ_INC_5_L51,  TOFFOLI_CLIFFT_CQ_INC_5_L52,  TOFFOLI_CLIFFT_CQ_INC_5_L53,
    TOFFOLI_CLIFFT_CQ_INC_5_L54,  TOFFOLI_CLIFFT_CQ_INC_5_L55,  TOFFOLI_CLIFFT_CQ_INC_5_L56,
    TOFFOLI_CLIFFT_CQ_INC_5_L57,  TOFFOLI_CLIFFT_CQ_INC_5_L58,  TOFFOLI_CLIFFT_CQ_INC_5_L59,
    TOFFOLI_CLIFFT_CQ_INC_5_L60,  TOFFOLI_CLIFFT_CQ_INC_5_L61,  TOFFOLI_CLIFFT_CQ_INC_5_L62,
    TOFFOLI_CLIFFT_CQ_INC_5_L63,  TOFFOLI_CLIFFT_CQ_INC_5_L64,  TOFFOLI_CLIFFT_CQ_INC_5_L65,
    TOFFOLI_CLIFFT_CQ_INC_5_L66,  TOFFOLI_CLIFFT_CQ_INC_5_L67,  TOFFOLI_CLIFFT_CQ_INC_5_L68,
    TOFFOLI_CLIFFT_CQ_INC_5_L69,  TOFFOLI_CLIFFT_CQ_INC_5_L70,  TOFFOLI_CLIFFT_CQ_INC_5_L71,
    TOFFOLI_CLIFFT_CQ_INC_5_L72,  TOFFOLI_CLIFFT_CQ_INC_5_L73,  TOFFOLI_CLIFFT_CQ_INC_5_L74,
    TOFFOLI_CLIFFT_CQ_INC_5_L75,  TOFFOLI_CLIFFT_CQ_INC_5_L76,  TOFFOLI_CLIFFT_CQ_INC_5_L77,
    TOFFOLI_CLIFFT_CQ_INC_5_L78,  TOFFOLI_CLIFFT_CQ_INC_5_L79,  TOFFOLI_CLIFFT_CQ_INC_5_L80,
    TOFFOLI_CLIFFT_CQ_INC_5_L81,  TOFFOLI_CLIFFT_CQ_INC_5_L82,  TOFFOLI_CLIFFT_CQ_INC_5_L83,
    TOFFOLI_CLIFFT_CQ_INC_5_L84,  TOFFOLI_CLIFFT_CQ_INC_5_L85,  TOFFOLI_CLIFFT_CQ_INC_5_L86,
    TOFFOLI_CLIFFT_CQ_INC_5_L87,  TOFFOLI_CLIFFT_CQ_INC_5_L88,  TOFFOLI_CLIFFT_CQ_INC_5_L89,
    TOFFOLI_CLIFFT_CQ_INC_5_L90,  TOFFOLI_CLIFFT_CQ_INC_5_L91,  TOFFOLI_CLIFFT_CQ_INC_5_L92,
    TOFFOLI_CLIFFT_CQ_INC_5_L93,  TOFFOLI_CLIFFT_CQ_INC_5_L94,  TOFFOLI_CLIFFT_CQ_INC_5_L95,
    TOFFOLI_CLIFFT_CQ_INC_5_L96,  TOFFOLI_CLIFFT_CQ_INC_5_L97,  TOFFOLI_CLIFFT_CQ_INC_5_L98,
    TOFFOLI_CLIFFT_CQ_INC_5_L99,  TOFFOLI_CLIFFT_CQ_INC_5_L100, TOFFOLI_CLIFFT_CQ_INC_5_L101,
    TOFFOLI_CLIFFT_CQ_INC_5_L102, TOFFOLI_CLIFFT_CQ_INC_5_L103, TOFFOLI_CLIFFT_CQ_INC_5_L104,
    TOFFOLI_CLIFFT_CQ_INC_5_L105, TOFFOLI_CLIFFT_CQ_INC_5_L106, TOFFOLI_CLIFFT_CQ_INC_5_L107,
    TOFFOLI_CLIFFT_CQ_INC_5_L108, TOFFOLI_CLIFFT_CQ_INC_5_L109, TOFFOLI_CLIFFT_CQ_INC_5_L110,
    TOFFOLI_CLIFFT_CQ_INC_5_L111, TOFFOLI_CLIFFT_CQ_INC_5_L112, TOFFOLI_CLIFFT_CQ_INC_5_L113,
    TOFFOLI_CLIFFT_CQ_INC_5_L114, TOFFOLI_CLIFFT_CQ_INC_5_L115, TOFFOLI_CLIFFT_CQ_INC_5_L116,
    TOFFOLI_CLIFFT_CQ_INC_5_L117, TOFFOLI_CLIFFT_CQ_INC_5_L118, TOFFOLI_CLIFFT_CQ_INC_5_L119,
    TOFFOLI_CLIFFT_CQ_INC_5_L120, TOFFOLI_CLIFFT_CQ_INC_5_L121, TOFFOLI_CLIFFT_CQ_INC_5_L122,
    TOFFOLI_CLIFFT_CQ_INC_5_L123, TOFFOLI_CLIFFT_CQ_INC_5_L124, TOFFOLI_CLIFFT_CQ_INC_5_L125,
    TOFFOLI_CLIFFT_CQ_INC_5_L126, TOFFOLI_CLIFFT_CQ_INC_5_L127, TOFFOLI_CLIFFT_CQ_INC_5_L128,
    TOFFOLI_CLIFFT_CQ_INC_5_L129, TOFFOLI_CLIFFT_CQ_INC_5_L130, TOFFOLI_CLIFFT_CQ_INC_5_L131,
    TOFFOLI_CLIFFT_CQ_INC_5_L132, TOFFOLI_CLIFFT_CQ_INC_5_L133, TOFFOLI_CLIFFT_CQ_INC_5_L134,
    TOFFOLI_CLIFFT_CQ_INC_5_L135, TOFFOLI_CLIFFT_CQ_INC_5_L136, TOFFOLI_CLIFFT_CQ_INC_5_L137,
    TOFFOLI_CLIFFT_CQ_INC_5_L138, TOFFOLI_CLIFFT_CQ_INC_5_L139, TOFFOLI_CLIFFT_CQ_INC_5_L140,
    TOFFOLI_CLIFFT_CQ_INC_5_L141, TOFFOLI_CLIFFT_CQ_INC_5_L142, TOFFOLI_CLIFFT_CQ_INC_5_L143,
    TOFFOLI_CLIFFT_CQ_INC_5_L144, TOFFOLI_CLIFFT_CQ_INC_5_L145, TOFFOLI_CLIFFT_CQ_INC_5_L146,
    TOFFOLI_CLIFFT_CQ_INC_5_L147, TOFFOLI_CLIFFT_CQ_INC_5_L148, TOFFOLI_CLIFFT_CQ_INC_5_L149,
    TOFFOLI_CLIFFT_CQ_INC_5_L150, TOFFOLI_CLIFFT_CQ_INC_5_L151, TOFFOLI_CLIFFT_CQ_INC_5_L152,
    TOFFOLI_CLIFFT_CQ_INC_5_L153, TOFFOLI_CLIFFT_CQ_INC_5_L154, TOFFOLI_CLIFFT_CQ_INC_5_L155,
    TOFFOLI_CLIFFT_CQ_INC_5_L156, TOFFOLI_CLIFFT_CQ_INC_5_L157, TOFFOLI_CLIFFT_CQ_INC_5_L158,
    TOFFOLI_CLIFFT_CQ_INC_5_L159, TOFFOLI_CLIFFT_CQ_INC_5_L160, TOFFOLI_CLIFFT_CQ_INC_5_L161,
    TOFFOLI_CLIFFT_CQ_INC_5_L162, TOFFOLI_CLIFFT_CQ_INC_5_L163};
static const num_t TOFFOLI_CLIFFT_CQ_INC_5_GPL[] = {
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};

static const sequence_t HARDCODED_TOFFOLI_CLIFFT_CQ_INC_5 = {
    .seq = (gate_t **)TOFFOLI_CLIFFT_CQ_INC_5_LAYERS,
    .num_layer = 164,
    .used_layer = 164,
    .gates_per_layer = (num_t *)TOFFOLI_CLIFFT_CQ_INC_5_GPL};

// ============================================================================
// DISPATCH HELPER FOR WIDTH 5
// ============================================================================

const sequence_t *get_hardcoded_toffoli_clifft_CQ_inc_5(int bits) {
    (void)bits;
    return &HARDCODED_TOFFOLI_CLIFFT_CQ_INC_5;
}

#endif // TOFFOLI_SEQ_WIDTH_5
