//
// toffoli_decomp_seq_5.c - MCX-decomposed Toffoli cQQ addition for 5-bit width
//
// Generated by scripts/generate_toffoli_decomp_seq.py - DO NOT EDIT MANUALLY
//
// Contains: Toffoli decomposed cQQ_add (static const, zero MCX)
// Algorithm: CDKM ripple-carry adder with AND-ancilla MCX decomposition
// All gates are X/CX/CCX (max 2 controls) -- no dynamic allocation needed.
//

#include "toffoli_sequences.h"

#ifdef TOFFOLI_SEQ_WIDTH_5

// ============================================================================
// TOFFOLI DECOMPOSED cQQ_ADD WIDTH 5 (50 layers)
// Qubit layout: [0,4] = target (a), [5,9] = source (b), [10] = carry, [11] = ext_ctrl, [12] =
// and_anc Total qubits: 13 All gates: CCX (max 2 controls) -- zero MCX, zero dynamic allocation
// ============================================================================

static const gate_t TOFFOLI_DECOMP_CQQ_5_L0[] = {{.Gate = X,
                                                  .Target = 5,
                                                  .NumControls = 2,
                                                  .Control = {0, 11},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L1[] = {{.Gate = X,
                                                  .Target = 10,
                                                  .NumControls = 2,
                                                  .Control = {0, 11},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L2[] = {{.Gate = X,
                                                  .Target = 12,
                                                  .NumControls = 2,
                                                  .Control = {10, 5},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L3[] = {{.Gate = X,
                                                  .Target = 0,
                                                  .NumControls = 2,
                                                  .Control = {12, 11},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L4[] = {{.Gate = X,
                                                  .Target = 12,
                                                  .NumControls = 2,
                                                  .Control = {10, 5},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L5[] = {{.Gate = X,
                                                  .Target = 6,
                                                  .NumControls = 2,
                                                  .Control = {1, 11},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L6[] = {{.Gate = X,
                                                  .Target = 0,
                                                  .NumControls = 2,
                                                  .Control = {1, 11},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L7[] = {{.Gate = X,
                                                  .Target = 12,
                                                  .NumControls = 2,
                                                  .Control = {0, 6},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L8[] = {{.Gate = X,
                                                  .Target = 1,
                                                  .NumControls = 2,
                                                  .Control = {12, 11},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L9[] = {{.Gate = X,
                                                  .Target = 12,
                                                  .NumControls = 2,
                                                  .Control = {0, 6},
                                                  .large_control = NULL,
                                                  .GateValue = 1,
                                                  .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L10[] = {{.Gate = X,
                                                   .Target = 7,
                                                   .NumControls = 2,
                                                   .Control = {2, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L11[] = {{.Gate = X,
                                                   .Target = 1,
                                                   .NumControls = 2,
                                                   .Control = {2, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L12[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {1, 7},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L13[] = {{.Gate = X,
                                                   .Target = 2,
                                                   .NumControls = 2,
                                                   .Control = {12, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L14[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {1, 7},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L15[] = {{.Gate = X,
                                                   .Target = 8,
                                                   .NumControls = 2,
                                                   .Control = {3, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L16[] = {{.Gate = X,
                                                   .Target = 2,
                                                   .NumControls = 2,
                                                   .Control = {3, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L17[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {2, 8},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L18[] = {{.Gate = X,
                                                   .Target = 3,
                                                   .NumControls = 2,
                                                   .Control = {12, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L19[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {2, 8},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L20[] = {{.Gate = X,
                                                   .Target = 9,
                                                   .NumControls = 2,
                                                   .Control = {4, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L21[] = {{.Gate = X,
                                                   .Target = 3,
                                                   .NumControls = 2,
                                                   .Control = {4, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L22[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {3, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L23[] = {{.Gate = X,
                                                   .Target = 4,
                                                   .NumControls = 2,
                                                   .Control = {12, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L24[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {3, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L25[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {3, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L26[] = {{.Gate = X,
                                                   .Target = 4,
                                                   .NumControls = 2,
                                                   .Control = {12, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L27[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {3, 9},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L28[] = {{.Gate = X,
                                                   .Target = 3,
                                                   .NumControls = 2,
                                                   .Control = {4, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L29[] = {{.Gate = X,
                                                   .Target = 9,
                                                   .NumControls = 2,
                                                   .Control = {3, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L30[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {2, 8},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L31[] = {{.Gate = X,
                                                   .Target = 3,
                                                   .NumControls = 2,
                                                   .Control = {12, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L32[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {2, 8},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L33[] = {{.Gate = X,
                                                   .Target = 2,
                                                   .NumControls = 2,
                                                   .Control = {3, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L34[] = {{.Gate = X,
                                                   .Target = 8,
                                                   .NumControls = 2,
                                                   .Control = {2, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L35[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {1, 7},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L36[] = {{.Gate = X,
                                                   .Target = 2,
                                                   .NumControls = 2,
                                                   .Control = {12, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L37[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {1, 7},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L38[] = {{.Gate = X,
                                                   .Target = 1,
                                                   .NumControls = 2,
                                                   .Control = {2, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L39[] = {{.Gate = X,
                                                   .Target = 7,
                                                   .NumControls = 2,
                                                   .Control = {1, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L40[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {0, 6},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L41[] = {{.Gate = X,
                                                   .Target = 1,
                                                   .NumControls = 2,
                                                   .Control = {12, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L42[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {0, 6},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L43[] = {{.Gate = X,
                                                   .Target = 0,
                                                   .NumControls = 2,
                                                   .Control = {1, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L44[] = {{.Gate = X,
                                                   .Target = 6,
                                                   .NumControls = 2,
                                                   .Control = {0, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L45[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {10, 5},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L46[] = {{.Gate = X,
                                                   .Target = 0,
                                                   .NumControls = 2,
                                                   .Control = {12, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L47[] = {{.Gate = X,
                                                   .Target = 12,
                                                   .NumControls = 2,
                                                   .Control = {10, 5},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L48[] = {{.Gate = X,
                                                   .Target = 10,
                                                   .NumControls = 2,
                                                   .Control = {0, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t TOFFOLI_DECOMP_CQQ_5_L49[] = {{.Gate = X,
                                                   .Target = 5,
                                                   .NumControls = 2,
                                                   .Control = {10, 11},
                                                   .large_control = NULL,
                                                   .GateValue = 1,
                                                   .NumBasisGates = 0}};

static const gate_t *TOFFOLI_DECOMP_CQQ_5_LAYERS[] = {
    TOFFOLI_DECOMP_CQQ_5_L0,  TOFFOLI_DECOMP_CQQ_5_L1,  TOFFOLI_DECOMP_CQQ_5_L2,
    TOFFOLI_DECOMP_CQQ_5_L3,  TOFFOLI_DECOMP_CQQ_5_L4,  TOFFOLI_DECOMP_CQQ_5_L5,
    TOFFOLI_DECOMP_CQQ_5_L6,  TOFFOLI_DECOMP_CQQ_5_L7,  TOFFOLI_DECOMP_CQQ_5_L8,
    TOFFOLI_DECOMP_CQQ_5_L9,  TOFFOLI_DECOMP_CQQ_5_L10, TOFFOLI_DECOMP_CQQ_5_L11,
    TOFFOLI_DECOMP_CQQ_5_L12, TOFFOLI_DECOMP_CQQ_5_L13, TOFFOLI_DECOMP_CQQ_5_L14,
    TOFFOLI_DECOMP_CQQ_5_L15, TOFFOLI_DECOMP_CQQ_5_L16, TOFFOLI_DECOMP_CQQ_5_L17,
    TOFFOLI_DECOMP_CQQ_5_L18, TOFFOLI_DECOMP_CQQ_5_L19, TOFFOLI_DECOMP_CQQ_5_L20,
    TOFFOLI_DECOMP_CQQ_5_L21, TOFFOLI_DECOMP_CQQ_5_L22, TOFFOLI_DECOMP_CQQ_5_L23,
    TOFFOLI_DECOMP_CQQ_5_L24, TOFFOLI_DECOMP_CQQ_5_L25, TOFFOLI_DECOMP_CQQ_5_L26,
    TOFFOLI_DECOMP_CQQ_5_L27, TOFFOLI_DECOMP_CQQ_5_L28, TOFFOLI_DECOMP_CQQ_5_L29,
    TOFFOLI_DECOMP_CQQ_5_L30, TOFFOLI_DECOMP_CQQ_5_L31, TOFFOLI_DECOMP_CQQ_5_L32,
    TOFFOLI_DECOMP_CQQ_5_L33, TOFFOLI_DECOMP_CQQ_5_L34, TOFFOLI_DECOMP_CQQ_5_L35,
    TOFFOLI_DECOMP_CQQ_5_L36, TOFFOLI_DECOMP_CQQ_5_L37, TOFFOLI_DECOMP_CQQ_5_L38,
    TOFFOLI_DECOMP_CQQ_5_L39, TOFFOLI_DECOMP_CQQ_5_L40, TOFFOLI_DECOMP_CQQ_5_L41,
    TOFFOLI_DECOMP_CQQ_5_L42, TOFFOLI_DECOMP_CQQ_5_L43, TOFFOLI_DECOMP_CQQ_5_L44,
    TOFFOLI_DECOMP_CQQ_5_L45, TOFFOLI_DECOMP_CQQ_5_L46, TOFFOLI_DECOMP_CQQ_5_L47,
    TOFFOLI_DECOMP_CQQ_5_L48, TOFFOLI_DECOMP_CQQ_5_L49};
static const num_t TOFFOLI_DECOMP_CQQ_5_GPL[] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};

static const sequence_t HARDCODED_TOFFOLI_DECOMP_CQQ_5 = {
    .seq = (gate_t **)TOFFOLI_DECOMP_CQQ_5_LAYERS,
    .num_layer = 50,
    .used_layer = 50,
    .gates_per_layer = (num_t *)TOFFOLI_DECOMP_CQQ_5_GPL};

// ============================================================================
// DISPATCH HELPER FOR WIDTH 5
// ============================================================================

const sequence_t *get_hardcoded_toffoli_decomp_cQQ_add_5(int bits) {
    (void)bits;
    return &HARDCODED_TOFFOLI_DECOMP_CQQ_5;
}

#endif // TOFFOLI_SEQ_WIDTH_5
