//
// toffoli_sequences.h - Hardcoded Toffoli gate sequences for CDKM addition
//
// This module provides pre-computed Toffoli gate sequences for CDKM
// ripple-carry addition up to 8-bit width. These avoid runtime
// malloc/build overhead for the most common Toffoli addition widths.
//
// Two variants are supported:
//   QQ_add  - Quantum-quantum CDKM addition (static const)
//   cQQ_add - Controlled quantum-quantum CDKM addition (dynamic init, cached)
//
// PUBLIC API:
//   get_hardcoded_toffoli_QQ_add(bits)  - Returns Toffoli QQ_add sequence or NULL
//   get_hardcoded_toffoli_cQQ_add(bits) - Returns Toffoli cQQ_add sequence or NULL
//
// Returns NULL for widths > TOFFOLI_HARDCODED_MAX_WIDTH (8).
// Caller must fall back to dynamic generation for NULL returns.
//
// IMPLEMENTATION:
//   - Per-width files: toffoli_add_seq_N.c (N=1..8), via #ifdef TOFFOLI_SEQ_WIDTH_N
//   - Unified dispatch: toffoli_add_seq_dispatch.c routes to per-width impls
//   - Define TOFFOLI_SEQ_NO_WIDTH_N before including to disable width N
//
// Generated by scripts/generate_toffoli_seq.py - DO NOT EDIT MANUALLY
//

#ifndef QUANTUM_TOFFOLI_SEQUENCES_H
#define QUANTUM_TOFFOLI_SEQUENCES_H

#include "types.h"

// ======================================================
// PREPROCESSOR GUARDS - All widths enabled by default
// Define TOFFOLI_SEQ_NO_WIDTH_N before including to disable width N
// ======================================================

#ifndef TOFFOLI_SEQ_NO_WIDTH_1
#define TOFFOLI_SEQ_WIDTH_1
#endif
#ifndef TOFFOLI_SEQ_NO_WIDTH_2
#define TOFFOLI_SEQ_WIDTH_2
#endif
#ifndef TOFFOLI_SEQ_NO_WIDTH_3
#define TOFFOLI_SEQ_WIDTH_3
#endif
#ifndef TOFFOLI_SEQ_NO_WIDTH_4
#define TOFFOLI_SEQ_WIDTH_4
#endif
#ifndef TOFFOLI_SEQ_NO_WIDTH_5
#define TOFFOLI_SEQ_WIDTH_5
#endif
#ifndef TOFFOLI_SEQ_NO_WIDTH_6
#define TOFFOLI_SEQ_WIDTH_6
#endif
#ifndef TOFFOLI_SEQ_NO_WIDTH_7
#define TOFFOLI_SEQ_WIDTH_7
#endif
#ifndef TOFFOLI_SEQ_NO_WIDTH_8
#define TOFFOLI_SEQ_WIDTH_8
#endif

// Maximum width for which hardcoded Toffoli sequences are available
#define TOFFOLI_HARDCODED_MAX_WIDTH 8

// ======================================================
// PUBLIC API - Original dispatch functions
// ======================================================

// Returns pre-computed Toffoli QQ_add sequence for given bit width
// Returns NULL if bits > TOFFOLI_HARDCODED_MAX_WIDTH or bits < 1
const sequence_t *get_hardcoded_toffoli_QQ_add(int bits);

// Returns pre-computed Toffoli cQQ_add (controlled QQ_add) sequence
// Returns NULL if bits > TOFFOLI_HARDCODED_MAX_WIDTH or bits < 1
const sequence_t *get_hardcoded_toffoli_cQQ_add(int bits);

// Returns pre-computed Toffoli CQ increment (value=1) sequence
// Returns NULL if bits > TOFFOLI_HARDCODED_MAX_WIDTH or bits < 1
const sequence_t *get_hardcoded_toffoli_CQ_inc(int bits);

// Returns pre-computed Toffoli cCQ increment (controlled, value=1) sequence
// Returns NULL if bits > TOFFOLI_HARDCODED_MAX_WIDTH or bits < 1
const sequence_t *get_hardcoded_toffoli_cCQ_inc(int bits);

// ======================================================
// PUBLIC API - MCX-decomposed dispatch functions (Phase 74-05)
// ======================================================

// Returns pre-computed MCX-decomposed Toffoli cQQ_add sequence.
// All gates are CCX (max 2 controls) -- zero MCX, zero dynamic allocation.
// Uses AND-ancilla qubit at position [2*bits+2].
// Returns NULL if bits > TOFFOLI_HARDCODED_MAX_WIDTH or bits < 1.
const sequence_t *get_hardcoded_toffoli_decomp_cQQ_add(int bits);

// ======================================================
// PUBLIC API - Clifford+T hardcoded dispatch functions (Phase 75)
// ======================================================

// CDKM Clifford+T sequences (widths 1-8)
const sequence_t *get_hardcoded_toffoli_clifft_QQ_add(int bits);
const sequence_t *get_hardcoded_toffoli_clifft_cQQ_add(int bits);
const sequence_t *get_hardcoded_toffoli_clifft_CQ_inc(int bits);
const sequence_t *get_hardcoded_toffoli_clifft_cCQ_inc(int bits);

// BK CLA Clifford+T sequences (widths 2-8, returns NULL for width 1)
const sequence_t *get_hardcoded_toffoli_clifft_cla_QQ_add(int bits);
const sequence_t *get_hardcoded_toffoli_clifft_cla_cQQ_add(int bits);
const sequence_t *get_hardcoded_toffoli_clifft_cla_CQ_inc(int bits);
const sequence_t *get_hardcoded_toffoli_clifft_cla_cCQ_inc(int bits);

#endif // QUANTUM_TOFFOLI_SEQUENCES_H
