#!/usr/bin/env python3
"""Toffoli CQ/cCQ increment Clifford+T generation script (widths 1-8).

This script generates per-width C source files for CQ and cCQ increment
(value=1) Clifford+T sequences, plus the unified CDKM Clifford+T dispatch file.

Generated files:
  - toffoli_clifft_cq_inc_N.c  (8 files) -- CQ increment Clifford+T
  - toffoli_clifft_ccq_inc_N.c (8 files) -- cCQ increment Clifford+T
  - toffoli_clifft_cdkm_dispatch.c       -- Unified dispatch for all 4 CDKM variants

The CQ/cCQ increment uses CDKM addition with value=1 classical-bit simplification:
  - Bit 0 skipped (carry=|0>), fold X-init at bit 1
  - Result: fewer gates than general QQ for the increment case

Gate encoding (Clifford+T):
  - H:   .Gate=H, .Target=t, .NumControls=0, .GateValue=0
  - T:   .Gate=T_GATE, .Target=t, .NumControls=0, .GateValue=M_PI/4.0
  - Tdg: .Gate=TDG_GATE, .Target=t, .NumControls=0, .GateValue=-M_PI/4.0
  - X:   .Gate=X, .Target=t, .NumControls=0, .GateValue=1
  - CX:  .Gate=X, .Target=t, .NumControls=1, .Control={c}, .GateValue=1

Usage:
  python scripts/generate_toffoli_clifft_cq_inc.py                  # Generate all files
  python scripts/generate_toffoli_clifft_cq_inc.py --width 4        # Generate only width 4
  python scripts/generate_toffoli_clifft_cq_inc.py --dry-run        # Print to stdout
  python scripts/generate_toffoli_clifft_cq_inc.py --validate       # Validate layer counts

Generated by: scripts/generate_toffoli_clifft_cq_inc.py
Phase 75, Plan 01: Clifford+T decomposed sequence generation for CDKM addition
"""

import argparse
import os
import sys
from dataclasses import dataclass, field

# ============================================================================
# Gate dataclasses
# ============================================================================


@dataclass
class ToffoliGate:
    """Represents a single gate in a Toffoli sequence (max 2 controls for static const)."""

    gate_type: str  # "X" (with controls: X, CX, CCX)
    target: int
    controls: list[int] = field(default_factory=list)

    @property
    def num_controls(self) -> int:
        return len(self.controls)


@dataclass
class CliffordTGate:
    """Gate in Clifford+T basis: H, T, Tdg, X (0 controls), CX (1 control)."""

    gate_type: str  # "H", "T", "Tdg", "X", "CX"
    target: int
    control: int = -1  # Only for CX

    def to_c_static(self) -> str:
        """Generate C static const initializer."""
        gate_enum = {
            "H": "H",
            "T": "T_GATE",
            "Tdg": "TDG_GATE",
            "X": "X",
            "CX": "X",  # CX is X with 1 control
        }[self.gate_type]

        gate_value = {
            "H": "0",
            "T": "M_PI / 4.0",
            "Tdg": "-M_PI / 4.0",
            "X": "1",
            "CX": "1",
        }[self.gate_type]

        num_controls = 1 if self.gate_type == "CX" else 0
        ctrl_init = f"{{{self.control}}}" if num_controls == 1 else "{0}"

        return (
            f"{{.Gate = {gate_enum},\n"
            f"                                      .Target = {self.target},\n"
            f"                                      .NumControls = {num_controls},\n"
            f"                                      .Control = {ctrl_init},\n"
            f"                                      .large_control = NULL,\n"
            f"                                      .GateValue = {gate_value},\n"
            f"                                      .NumBasisGates = 0}}"
        )


def ccx_to_clifford_t(target: int, ctrl1: int, ctrl2: int) -> list[CliffordTGate]:
    """Expand CCX(target, ctrl1, ctrl2) into 15 Clifford+T gates.

    Sequence matches gate.c:emit_ccx_clifford_t exactly.
    """
    return [
        CliffordTGate("H", target),
        CliffordTGate("CX", target, ctrl2),
        CliffordTGate("Tdg", target),
        CliffordTGate("CX", target, ctrl1),
        CliffordTGate("T", target),
        CliffordTGate("CX", target, ctrl2),
        CliffordTGate("Tdg", target),
        CliffordTGate("CX", target, ctrl1),
        CliffordTGate("T", target),
        CliffordTGate("T", ctrl2),
        CliffordTGate("H", target),
        CliffordTGate("CX", ctrl2, ctrl1),
        CliffordTGate("T", ctrl1),
        CliffordTGate("Tdg", ctrl2),
        CliffordTGate("CX", ctrl2, ctrl1),
    ]


def toffoli_to_clifford_t(gates: list[ToffoliGate]) -> list[CliffordTGate]:
    """Convert a list of ToffoliGate (X/CX/CCX) to CliffordTGate (H/T/Tdg/X/CX).

    CX and X gates pass through. CCX gates expand to 15 Clifford+T gates.
    """
    result = []
    for gate in gates:
        if gate.num_controls == 0:
            result.append(CliffordTGate("X", gate.target))
        elif gate.num_controls == 1:
            result.append(CliffordTGate("CX", gate.target, gate.controls[0]))
        elif gate.num_controls == 2:
            result.extend(ccx_to_clifford_t(gate.target, gate.controls[0], gate.controls[1]))
        else:
            raise ValueError(
                f"Cannot convert gate with {gate.num_controls} controls to Clifford+T."
            )
    return result


# ============================================================================
# CDKM CQ increment (value=1) gate generation with classical-bit simplification
# ============================================================================


def generate_cq_inc_gates(bits: int) -> list[ToffoliGate]:
    """Generate CQ increment (value=1) CDKM gate sequence.

    Qubit layout:
      [0..bits-1]       = temp register (classical init)
      [bits..2*bits-1]  = self register (quantum target)
      [2*bits]          = carry ancilla (bits >= 2)

    Width 1: single X(target=0) -- increment by 1 on 1-bit register
    Width N >= 2: CDKM with classical-bit simplification for value=1

    Classical-bit simplification for value=1 (binary = ...0001):
      - LSB (bit 0) = 1: skip MAJ at bit 0 (carry=|0>), fold X-init
      - All higher bits = 0: standard MAJ/UMA (no classical simplification)
    """
    gates = []

    if bits == 1:
        # Single X: self[0] ^= 1
        gates.append(ToffoliGate("X", target=0, controls=[]))
        return gates

    carry = 2 * bits

    # X-init temp[0] to classical bit 0 = 1
    gates.append(ToffoliGate("X", target=0, controls=[]))

    # Bit 0: classical bit = 1, carry-in = |0>
    # Skip MAJ at bit 0 (carry=|0>, so CCX with carry control never triggers)
    # Fold: CX(self[0], temp[0]) and CX(carry, temp[0]) simplified to:
    # X(self[0]) -- always flip self[0] since temp[0]=1 and carry=0
    # X(carry) -- carry gets the AND of temp[0] and self[0] original
    # Actually, the CDKM CQ for value=1 bit=0 uses:
    #   X-init temp[0]
    #   MAJ simplified: CX(self[0], temp[0]) is done but CCX(temp[0], carry, self[0]) has carry=|0>
    #   -> Simplified to: just set carry based on temp[0] AND self[0]
    # The actual pattern from toffoli_cq_inc_seq_2.c width 2:
    #   X(0), X(2), X(4), CCX(0,[4,2]), CCX(1,[0,3]), CCX(1,[0,3]), CX(0,[1]), CX(3,[0]),
    #   CCX(0,[4,2]), CX(4,[0]), CX(2,[4]), X(0)
    # Which is: X-init(temp[0]), X(self[0]), X(carry), CCX(temp[0],[carry,self[0]]),
    #   then standard MAJ(temp[0],self[1],temp[1]), UMA(temp[0],self[1],temp[1]),
    #   UMA(carry,self[0],temp[0]) with X-cleanup
    # Let me trace exactly from the existing files:

    # From toffoli_cq_inc_seq_2.c:
    # L0: X(0)         -- X-init temp[0] (classical bit 0 = 1)
    # L1: X(2)         -- X(self[0])
    # L2: X(4)         -- X(carry)
    # L3: CCX(0,[4,2]) -- CCX(temp[0], carry, self[0])
    # -- This is the "folded" MAJ at bit 0: effectively temp[0]=carry_out, carry is updated
    # L4: CCX(1,[0,3]) -- MAJ(temp[0], self[1], temp[1]): CX(self[1],temp[1]) part = CCX here?
    # Wait, this doesn't match MAJ pattern. Let me re-read more carefully.

    # Looking at toffoli_cq_inc_seq_3.c width 3 (16 layers):
    # L0:  X(0)          -- init temp[0] = 1
    # L1:  X(3)          -- X(self[0])
    # L2:  X(6)          -- X(carry)
    # L3:  CCX(0,[6,3])  -- CCX(temp[0],[carry,self[0]])  = "folded MAJ at bit 0"
    # L4:  CCX(1,[0,4])  -- at bit 1: MAJ(temp[0], self[1], temp[1])
    # L5:  CCX(2,[1,5])  -- at bit 2: MAJ(temp[1], self[2], temp[2])
    # L6:  CCX(2,[1,5])  -- UMA at bit 2 step 1: CCX(temp[2],[temp[1],self[2]])
    # L7:  CX(1,[2])     -- UMA at bit 2 step 2: CX(temp[1],[temp[2]])
    # L8:  CX(5,[1])     -- UMA at bit 2 step 3: CX(self[2],[temp[1]])
    # L9:  CCX(1,[0,4])  -- UMA at bit 1 step 1: CCX(temp[1],[temp[0],self[1]])
    # L10: CX(0,[1])     -- UMA at bit 1 step 2: CX(temp[0],[temp[1]])
    # L11: CX(4,[0])     -- UMA at bit 1 step 3: CX(self[1],[temp[0]])
    # L12: CCX(0,[6,3])  -- "folded UMA at bit 0": CCX(temp[0],[carry,self[0]])
    # L13: CX(6,[0])     -- UMA at bit 0 step 2: CX(carry,[temp[0]])
    # L14: CX(3,[6])     -- UMA at bit 0 step 3: CX(self[0],[carry])
    # L15: X(0)          -- X-cleanup temp[0]

    # Pattern for CQ inc value=1, bits >= 2:
    # 1. X-init temp[0] (classical bit 0 = 1)
    # 2. X(self[0]) and X(carry) -- fold the MAJ at bit 0
    # 3. CCX(temp[0], carry, self[0]) -- completes the "folded MAJ" at bit 0
    # 4. For bits 1..bits-1: standard MAJ (just the CCX part)
    #    MAJ(temp[i-1], self[i], temp[i]) = CCX(temp[i], temp[i-1], self[i])
    # 5. Reverse UMA sweep for bits bits-1..1:
    #    UMA(temp[i-1], self[i], temp[i]) = CCX(temp[i], temp[i-1], self[i]), CX(temp[i-1], temp[i]), CX(self[i], temp[i-1])
    # 6. "Folded UMA" at bit 0:
    #    CCX(temp[0], carry, self[0]), CX(carry, temp[0]), CX(self[0], carry)
    # 7. X-cleanup temp[0]

    # X(self[0]) and X(carry)
    gates.append(ToffoliGate("X", target=bits, controls=[]))  # X(self[0])
    gates.append(ToffoliGate("X", target=carry, controls=[]))  # X(carry)

    # Folded MAJ at bit 0: CCX(temp[0], carry, self[0])
    gates.append(ToffoliGate("X", target=0, controls=[carry, bits]))

    # Standard MAJ for bits 1..bits-1 (simplified: just CCX)
    for i in range(1, bits):
        # MAJ(temp[i-1], self[i], temp[i]) simplified to just CCX
        # CCX(temp[i], temp[i-1], self[i])
        gates.append(ToffoliGate("X", target=i, controls=[i - 1, bits + i]))

    # Reverse UMA sweep for bits bits-1..1
    for i in range(bits - 1, 0, -1):
        # UMA(temp[i-1], self[i], temp[i]):
        #   CCX(temp[i], temp[i-1], self[i])
        #   CX(temp[i-1], temp[i])
        #   CX(self[i], temp[i-1])
        gates.append(ToffoliGate("X", target=i, controls=[i - 1, bits + i]))
        gates.append(ToffoliGate("X", target=i - 1, controls=[i]))
        gates.append(ToffoliGate("X", target=bits + i, controls=[i - 1]))

    # Folded UMA at bit 0: CCX(temp[0], carry, self[0]), CX(carry, temp[0]), CX(self[0], carry)
    gates.append(ToffoliGate("X", target=0, controls=[carry, bits]))
    gates.append(ToffoliGate("X", target=carry, controls=[0]))
    gates.append(ToffoliGate("X", target=bits, controls=[carry]))

    # X-cleanup temp[0]
    gates.append(ToffoliGate("X", target=0, controls=[]))

    return gates


def generate_ccq_inc_gates(bits: int) -> list[ToffoliGate]:
    """Generate cCQ increment (value=1, controlled) CDKM gate sequence.

    Qubit layout:
      [0..bits-1]       = temp register
      [bits..2*bits-1]  = self register (quantum target)
      [2*bits]          = carry ancilla (bits >= 2)
      [2*bits+1]        = external control qubit

    Width 1: single CX(target=0, control=1)
    Width N >= 2: controlled CDKM increment with classical-bit simplification

    The controlled version replaces:
      X -> CX(target, ext_ctrl)
      CX -> CCX(target, ctrl, ext_ctrl)
      CCX -> MCX -> AND-decomposed -> 3 CCX via and_anc

    But since we're generating for Clifford+T, and cCQ inc files need to be
    static const (no MCX), we use the AND-ancilla decomposition pattern:
      - MCX(target, [c1, c2, ext_ctrl]) -> CCX(and_anc, c1, c2), CCX(target, and_anc, ext_ctrl), CCX(and_anc, c1, c2)
    Then all CCX -> 15 Clifford+T gates.

    For the Clifford+T version, we generate the controlled gate sequence
    using the decomposition pattern from the cCQ inc files.
    """
    gates = []

    if bits == 1:
        # Single CX: controlled self[0] ^= 1
        gates.append(ToffoliGate("X", target=0, controls=[1]))
        return gates

    carry = 2 * bits
    ext_ctrl = 2 * bits + 1

    # CX-init temp[0] (controlled by ext_ctrl)
    gates.append(ToffoliGate("X", target=0, controls=[ext_ctrl]))

    # Bit 0: controlled X(self[0]) and X(carry) become CCX
    gates.append(ToffoliGate("X", target=bits, controls=[0, ext_ctrl]))  # CCX
    gates.append(ToffoliGate("X", target=carry, controls=[0, ext_ctrl]))  # CCX

    # Folded cMAJ at bit 0: MCX(temp[0], [carry, self[0], ext_ctrl])
    # -> AND-decompose: CCX(and_anc, carry, self[0]), CCX(temp[0], and_anc, ext_ctrl),
    #                   CCX(and_anc, carry, self[0])
    # But we don't have and_anc in the qubit layout for cCQ inc!
    # Looking at existing cCQ inc files: they use MCX(3 controls) directly.
    # For Clifford+T we need AND-ancilla. Let me check qubit layout.
    #
    # From plan: "Qubit layout: [0..N-1] = temp, [N..2N-1] = self, [2N] = carry,
    #            [2N+1] = ext_ctrl, [2N+2] = AND-ancilla"
    # So we DO have and_anc at position 2*bits+2 for the Clifford+T version.
    and_anc = 2 * bits + 2

    # Folded cMAJ at bit 0: MCX(temp[0], [carry, self[0], ext_ctrl])
    # AND-decompose: CCX(and_anc, carry, self[0]), CCX(temp[0], and_anc, ext_ctrl), CCX(and_anc, carry, self[0])
    gates.append(ToffoliGate("X", target=and_anc, controls=[carry, bits]))
    gates.append(ToffoliGate("X", target=0, controls=[and_anc, ext_ctrl]))
    gates.append(ToffoliGate("X", target=and_anc, controls=[carry, bits]))

    # Standard cMAJ for bits 1..bits-1:
    # Each cMAJ(temp[i-1], self[i], temp[i], ext_ctrl) with AND-ancilla decomposition
    # Original gate: MCX(temp[i], [temp[i-1], self[i], ext_ctrl])
    # -> CCX(and_anc, temp[i-1], self[i]), CCX(temp[i], and_anc, ext_ctrl), CCX(and_anc, temp[i-1], self[i])
    for i in range(1, bits):
        gates.append(ToffoliGate("X", target=and_anc, controls=[i - 1, bits + i]))
        gates.append(ToffoliGate("X", target=i, controls=[and_anc, ext_ctrl]))
        gates.append(ToffoliGate("X", target=and_anc, controls=[i - 1, bits + i]))

    # Reverse cUMA sweep for bits bits-1..1
    # cUMA(temp[i-1], self[i], temp[i], ext_ctrl):
    #   MCX(temp[i], [temp[i-1], self[i], ext_ctrl]) -> 3 CCX via AND-ancilla
    #   CCX(temp[i-1], temp[i], ext_ctrl)
    #   CCX(self[i], temp[i-1], ext_ctrl)
    for i in range(bits - 1, 0, -1):
        # MCX decomposition
        gates.append(ToffoliGate("X", target=and_anc, controls=[i - 1, bits + i]))
        gates.append(ToffoliGate("X", target=i, controls=[and_anc, ext_ctrl]))
        gates.append(ToffoliGate("X", target=and_anc, controls=[i - 1, bits + i]))
        # CCX(temp[i-1], temp[i], ext_ctrl)
        gates.append(ToffoliGate("X", target=i - 1, controls=[i, ext_ctrl]))
        # CCX(self[i], temp[i-1], ext_ctrl)
        gates.append(ToffoliGate("X", target=bits + i, controls=[i - 1, ext_ctrl]))

    # Folded cUMA at bit 0: MCX(temp[0], [carry, self[0], ext_ctrl])
    # -> AND-decompose
    gates.append(ToffoliGate("X", target=and_anc, controls=[carry, bits]))
    gates.append(ToffoliGate("X", target=0, controls=[and_anc, ext_ctrl]))
    gates.append(ToffoliGate("X", target=and_anc, controls=[carry, bits]))
    # CCX(carry, temp[0], ext_ctrl)
    gates.append(ToffoliGate("X", target=carry, controls=[0, ext_ctrl]))
    # CCX(self[0], carry, ext_ctrl)
    gates.append(ToffoliGate("X", target=bits, controls=[carry, ext_ctrl]))

    # CX-cleanup temp[0]
    gates.append(ToffoliGate("X", target=0, controls=[ext_ctrl]))

    return gates


# ============================================================================
# C code generation for Clifford+T (static const)
# ============================================================================


def generate_clifft_static_c(gates: list[CliffordTGate], prefix: str, width: int) -> str:
    """Generate static const C code for a Clifford+T sequence."""
    lines = []
    num_layers = len(gates)

    # Each gate is on its own layer
    for i, gate in enumerate(gates):
        gate_str = gate.to_c_static()
        lines.append(f"static const gate_t {prefix}_{width}_L{i}[] = {{{gate_str}}};")
        lines.append("")

    # Layer pointer array
    if num_layers > 6:
        chunks = [list(range(i, min(i + 6, num_layers))) for i in range(0, num_layers, 6)]
        chunk_lines = []
        for chunk in chunks:
            names = ", ".join(f"{prefix}_{width}_L{j}" for j in chunk)
            chunk_lines.append(f"    {names}")
        layers_str = ",\n".join(chunk_lines)
        lines.append(f"static const gate_t *{prefix}_{width}_LAYERS[] = {{\n{layers_str}}};")
    else:
        names = ", ".join(f"{prefix}_{width}_L{i}" for i in range(num_layers))
        lines.append(f"static const gate_t *{prefix}_{width}_LAYERS[] = {{{names}}};")

    # Gates per layer array (all 1s)
    gpl_str = ", ".join("1" for _ in range(num_layers))
    lines.append(f"static const num_t {prefix}_{width}_GPL[] = {{{gpl_str}}};")
    lines.append("")

    # Sequence struct
    lines.append(
        f"static const sequence_t HARDCODED_{prefix}_{width} = "
        f"{{.seq = (gate_t **){prefix}_{width}_LAYERS,"
    )
    lines.append(f"                                              .num_layer = {num_layers},")
    lines.append(f"                                              .used_layer = {num_layers},")
    lines.append(
        f"                                              .gates_per_layer = "
        f"(num_t *){prefix}_{width}_GPL}};"
    )

    return "\n".join(lines)


# ============================================================================
# Per-width file generation: CQ inc Clifford+T
# ============================================================================


def generate_cq_inc_width_file(width: int) -> str:
    """Generate complete C source file for CQ inc Clifford+T at one width."""
    output = []

    output.append("//")
    output.append(
        f"// toffoli_clifft_cq_inc_{width}.c - CDKM CQ increment Clifford+T for {width}-bit width"
    )
    output.append("//")
    output.append(
        "// Generated by scripts/generate_toffoli_clifft_cq_inc.py - DO NOT EDIT MANUALLY"
    )
    output.append("//")
    output.append(
        "// Contains: Toffoli CDKM CQ increment (value=1) Clifford+T (static const, zero CCX)"
    )
    output.append(
        "// Algorithm: CDKM ripple-carry adder with classical-bit simplification + CCX->Clifford+T"
    )
    output.append("// All gates: H/T/Tdg/CX/X (max 1 control) -- fully static const.")
    output.append("//")
    output.append("")
    output.append('#include "toffoli_sequences.h"')
    output.append("")
    output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")
    if width >= 2:
        output.append("#include <math.h>")
        output.append("")

    # Generate gate sequences
    cq_gates = generate_cq_inc_gates(width)
    clifft_gates = toffoli_to_clifford_t(cq_gates)

    if width == 1:
        cq_num_qubits = 1
    else:
        cq_num_qubits = 2 * width + 1
    output.append("// ============================================================================")
    output.append(f"// TOFFOLI CLIFFT CQ_INC WIDTH {width} ({len(clifft_gates)} layers)")
    if width == 1:
        output.append("// Qubit layout: [0] = self")
    else:
        output.append(
            f"// Qubit layout: [0,{width - 1}] = temp, "
            f"[{width},{2 * width - 1}] = self, [{2 * width}] = carry"
        )
    output.append(f"// Total qubits: {cq_num_qubits}")
    output.append("// All gates: H/T/Tdg/CX/X (max 1 control) -- zero CCX")
    output.append("// ============================================================================")
    output.append("")
    output.append(generate_clifft_static_c(clifft_gates, "TOFFOLI_CLIFFT_CQ_INC", width))
    output.append("")

    # Dispatch helper
    output.append("// ============================================================================")
    output.append(f"// DISPATCH HELPER FOR WIDTH {width}")
    output.append("// ============================================================================")
    output.append("")
    output.append(f"const sequence_t *get_hardcoded_toffoli_clifft_CQ_inc_{width}(int bits) {{")
    output.append("    (void)bits;")
    output.append(f"    return &HARDCODED_TOFFOLI_CLIFFT_CQ_INC_{width};")
    output.append("}")
    output.append("")

    output.append(f"#endif // TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")

    return "\n".join(output)


# ============================================================================
# Per-width file generation: cCQ inc Clifford+T
# ============================================================================


def generate_ccq_inc_width_file(width: int) -> str:
    """Generate complete C source file for cCQ inc Clifford+T at one width."""
    output = []

    output.append("//")
    output.append(
        f"// toffoli_clifft_ccq_inc_{width}.c - CDKM cCQ increment Clifford+T for {width}-bit width"
    )
    output.append("//")
    output.append(
        "// Generated by scripts/generate_toffoli_clifft_cq_inc.py - DO NOT EDIT MANUALLY"
    )
    output.append("//")
    output.append(
        "// Contains: Toffoli CDKM cCQ increment (value=1) Clifford+T (static const, zero CCX/MCX)"
    )
    output.append(
        "// Algorithm: CDKM ripple-carry adder with AND-ancilla MCX decomposition + CCX->Clifford+T"
    )
    output.append("// All gates: H/T/Tdg/CX/X (max 1 control) -- fully static const.")
    output.append("//")
    output.append("")
    output.append('#include "toffoli_sequences.h"')
    output.append("")
    output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")
    if width >= 2:
        output.append("#include <math.h>")
        output.append("")

    # Generate gate sequences
    ccq_gates = generate_ccq_inc_gates(width)
    clifft_gates = toffoli_to_clifford_t(ccq_gates)

    if width == 1:
        ccq_num_qubits = 2
    else:
        ccq_num_qubits = 2 * width + 3
    output.append("// ============================================================================")
    output.append(f"// TOFFOLI CLIFFT cCQ_INC WIDTH {width} ({len(clifft_gates)} layers)")
    if width == 1:
        output.append("// Qubit layout: [0] = self, [1] = ext_ctrl")
    else:
        output.append(
            f"// Qubit layout: [0,{width - 1}] = temp, "
            f"[{width},{2 * width - 1}] = self, [{2 * width}] = carry, "
            f"[{2 * width + 1}] = ext_ctrl, [{2 * width + 2}] = and_anc"
        )
    output.append(f"// Total qubits: {ccq_num_qubits}")
    output.append("// All gates: H/T/Tdg/CX/X (max 1 control) -- zero CCX, zero MCX")
    output.append("// ============================================================================")
    output.append("")
    output.append(generate_clifft_static_c(clifft_gates, "TOFFOLI_CLIFFT_CCQ_INC", width))
    output.append("")

    # Dispatch helper
    output.append("// ============================================================================")
    output.append(f"// DISPATCH HELPER FOR WIDTH {width}")
    output.append("// ============================================================================")
    output.append("")
    output.append(f"const sequence_t *get_hardcoded_toffoli_clifft_cCQ_inc_{width}(int bits) {{")
    output.append("    (void)bits;")
    output.append(f"    return &HARDCODED_TOFFOLI_CLIFFT_CCQ_INC_{width};")
    output.append("}")
    output.append("")

    output.append(f"#endif // TOFFOLI_SEQ_WIDTH_{width}")
    output.append("")

    return "\n".join(output)


# ============================================================================
# Unified CDKM Clifford+T dispatch file generation
# ============================================================================


def generate_dispatch_file(max_width: int = 8) -> str:
    """Generate toffoli_clifft_cdkm_dispatch.c with unified dispatch for all 4 variants."""
    output = []

    output.append("//")
    output.append(
        "// toffoli_clifft_cdkm_dispatch.c - Unified dispatch for all CDKM Clifford+T sequences"
    )
    output.append("//")
    output.append(
        "// Generated by scripts/generate_toffoli_clifft_cq_inc.py - DO NOT EDIT MANUALLY"
    )
    output.append("//")
    output.append("// Routes get_hardcoded_toffoli_clifft_*() calls to per-width implementations.")
    output.append(
        "// Each per-width file is conditionally compiled via #ifdef TOFFOLI_SEQ_WIDTH_N."
    )
    output.append("//")
    output.append("")
    output.append('#include "toffoli_sequences.h"')
    output.append("#include <stddef.h>")
    output.append("")

    # Forward declarations for all 4 variants
    variants = [
        ("QQ_add", "toffoli_clifft_QQ_add"),
        ("cQQ_add", "toffoli_clifft_cQQ_add"),
        ("CQ_inc", "toffoli_clifft_CQ_inc"),
        ("cCQ_inc", "toffoli_clifft_cCQ_inc"),
    ]

    output.append("// ============================================================================")
    output.append("// FORWARD DECLARATIONS (conditionally compiled per width)")
    output.append("// ============================================================================")
    output.append("")

    for _label, func_name in variants:
        for w in range(1, max_width + 1):
            output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{w}")
            output.append(f"const sequence_t *get_hardcoded_{func_name}_{w}(int bits);")
            output.append("#endif")
        output.append("")

    # Dispatch functions
    for label, func_name in variants:
        output.append(
            "// ============================================================================"
        )
        output.append(f"// UNIFIED TOFFOLI CLIFFT {label} DISPATCH")
        output.append(
            "// ============================================================================"
        )
        output.append("")
        output.append(f"const sequence_t *get_hardcoded_{func_name}(int bits) {{")
        output.append("    switch (bits) {")
        for w in range(1, max_width + 1):
            output.append(f"#ifdef TOFFOLI_SEQ_WIDTH_{w}")
            output.append(f"    case {w}: return get_hardcoded_{func_name}_{w}(bits);")
            output.append("#endif")
        output.append("    default: return NULL;")
        output.append("    }")
        output.append("}")
        output.append("")

    return "\n".join(output)


# ============================================================================
# Validation
# ============================================================================


def validate(max_width: int = 8) -> bool:
    """Validate CQ/cCQ increment Clifford+T gate sequences."""
    all_ok = True

    # CQ inc layer counts
    print("=" * 60)
    print("Clifford+T CQ_inc layer count validation")
    print("=" * 60)
    for w in range(1, max_width + 1):
        cq_gates = generate_cq_inc_gates(w)
        clifft_gates = toffoli_to_clifford_t(cq_gates)
        actual = len(clifft_gates)
        # Count gate types in source
        x_count = sum(1 for g in cq_gates if g.num_controls == 0)
        cx_count = sum(1 for g in cq_gates if g.num_controls == 1)
        ccx_count = sum(1 for g in cq_gates if g.num_controls == 2)
        expected = x_count + cx_count + ccx_count * 15
        status = "OK" if actual == expected else "MISMATCH"
        if actual != expected:
            all_ok = False
        print(
            f"  width {w:2d}: {actual:4d} layers  "
            f"(src: X={x_count}, CX={cx_count}, CCX={ccx_count})  "
            f"expected {expected:4d}  [{status}]"
        )

    print()

    # cCQ inc layer counts
    print("=" * 60)
    print("Clifford+T cCQ_inc layer count validation")
    print("=" * 60)
    for w in range(1, max_width + 1):
        ccq_gates = generate_ccq_inc_gates(w)
        clifft_gates = toffoli_to_clifford_t(ccq_gates)
        actual = len(clifft_gates)
        x_count = sum(1 for g in ccq_gates if g.num_controls == 0)
        cx_count = sum(1 for g in ccq_gates if g.num_controls == 1)
        ccx_count = sum(1 for g in ccq_gates if g.num_controls == 2)
        expected = x_count + cx_count + ccx_count * 15
        status = "OK" if actual == expected else "MISMATCH"
        if actual != expected:
            all_ok = False
        print(
            f"  width {w:2d}: {actual:4d} layers  "
            f"(src: X={x_count}, CX={cx_count}, CCX={ccx_count})  "
            f"expected {expected:4d}  [{status}]"
        )

    print()

    # Verify max 1 control in Clifford+T gates
    print("=" * 60)
    print("Clifford+T CQ/cCQ inc gate control count (must be <= 1)")
    print("=" * 60)
    for w in range(1, max_width + 1):
        cq_gates = generate_cq_inc_gates(w)
        cq_clifft = toffoli_to_clifford_t(cq_gates)
        ccq_gates = generate_ccq_inc_gates(w)
        ccq_clifft = toffoli_to_clifford_t(ccq_gates)

        cq_max = max((1 if g.gate_type == "CX" else 0) for g in cq_clifft)
        ccq_max = max((1 if g.gate_type == "CX" else 0) for g in ccq_clifft)
        ok = cq_max <= 1 and ccq_max <= 1
        status = "OK" if ok else "FAIL"
        if not ok:
            all_ok = False
        print(f"  width {w:2d}: CQ max={cq_max}, cCQ max={ccq_max}  [{status}]")

    print()

    # Verify source gate counts match existing toffoli_cq_inc_seq_*.c
    print("=" * 60)
    print("CQ inc source gate count verification (vs existing files)")
    print("=" * 60)
    # Width 1: CQ = 1 gate (X), cCQ = 1 gate (CX)
    # Width 2: CQ = 12 gates (from toffoli_cq_inc_seq_2.c), cCQ = 12 gates
    # Width 3: CQ = 16 gates, cCQ = 16 gates
    # Width N >= 2: CQ = 4 + 4*(N-1) = 4N gates from gate analysis
    #   init: X(temp[0]), X(self[0]), X(carry) = 3 X
    #   folded MAJ bit 0: 1 CCX
    #   MAJ bits 1..N-1: (N-1) CCX
    #   UMA bits N-1..1: (N-1) * (CCX + CX + CX) = (N-1)*3 gates
    #   folded UMA bit 0: CCX + CX + CX = 3 gates
    #   cleanup: X(temp[0]) = 1 X
    #   Total: 3 + 1 + (N-1) + 3*(N-1) + 3 + 1 = 4 + N-1 + 3N-3 + 3 = 4N + 3
    # Wait, let me count for width 2:
    #   3 X + 1 CCX + 1 CCX (bits 1..1) + 1*(CCX+CX+CX) + (CCX+CX+CX) + 1 X
    #   = 4 + 2 + 3 + 3 = 12. Correct!
    # Width 3:
    #   3 X + 1 CCX + 2 CCX + 2*(CCX+CX+CX) + (CCX+CX+CX) + 1 X
    #   = 4 + 3 + 6 + 3 = 16. Correct!
    for w in range(1, max_width + 1):
        cq_gates = generate_cq_inc_gates(w)
        actual = len(cq_gates)
        if w == 1:
            expected = 1
        else:
            expected = 4 * w + 4
        status = "OK" if actual == expected else "MISMATCH"
        if actual != expected:
            all_ok = False
        print(f"  CQ  width {w:2d}: {actual:4d} gates  expected {expected:4d}  [{status}]")

    print()

    # Gate type distribution
    print("=" * 60)
    print("Clifford+T CQ/cCQ inc gate type distribution")
    print("=" * 60)
    for w in range(1, max_width + 1):
        cq_gates = generate_cq_inc_gates(w)
        cq_clifft = toffoli_to_clifford_t(cq_gates)
        counts = {"H": 0, "T": 0, "Tdg": 0, "X": 0, "CX": 0}
        for g in cq_clifft:
            counts[g.gate_type] += 1
        parts = ", ".join(f"{k}={v}" for k, v in counts.items() if v > 0)
        print(f"  CQ  width {w:2d}: {parts}, total={len(cq_clifft)}")

        ccq_gates = generate_ccq_inc_gates(w)
        ccq_clifft = toffoli_to_clifford_t(ccq_gates)
        counts = {"H": 0, "T": 0, "Tdg": 0, "X": 0, "CX": 0}
        for g in ccq_clifft:
            counts[g.gate_type] += 1
        parts = ", ".join(f"{k}={v}" for k, v in counts.items() if v > 0)
        print(f"  cCQ width {w:2d}: {parts}, total={len(ccq_clifft)}")

    print()

    if all_ok:
        print("ALL CQ/cCQ INC CLIFFORD+T VALIDATIONS PASSED")
    else:
        print("CQ/cCQ INC CLIFFORD+T VALIDATION FAILED - see mismatches above")

    return all_ok


# ============================================================================
# CLI entry point
# ============================================================================


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Generate CDKM CQ/cCQ increment Clifford+T sequence C files "
            "for widths 1-8, plus unified CDKM Clifford+T dispatch."
        )
    )
    parser.add_argument(
        "--width",
        type=int,
        metavar="N",
        help="Generate only for width N (default: all 1-8)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print to stdout instead of writing files",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Output directory for C files (default: c_backend/src/sequences/)",
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Cross-validate against expected layer counts",
    )
    parser.add_argument(
        "--max-width",
        type=int,
        default=8,
        help="Maximum width to generate (default: 8)",
    )

    args = parser.parse_args()

    if args.validate:
        ok = validate(args.max_width)
        sys.exit(0 if ok else 1)

    # Determine output directory
    script_dir = os.path.dirname(os.path.abspath(__file__))

    if args.output_dir:
        output_dir = args.output_dir
    else:
        output_dir = os.path.normpath(
            os.path.join(script_dir, "..", "c_backend", "src", "sequences")
        )

    max_width = args.max_width

    if args.width:
        if args.width < 1 or args.width > max_width:
            print(f"Error: width must be 1-{max_width}", file=sys.stderr)
            sys.exit(1)
        cq_content = generate_cq_inc_width_file(args.width)
        ccq_content = generate_ccq_inc_width_file(args.width)
        if args.dry_run:
            print(f"// === FILE: toffoli_clifft_cq_inc_{args.width}.c ===")
            print(cq_content)
            print()
            print(f"// === FILE: toffoli_clifft_ccq_inc_{args.width}.c ===")
            print(ccq_content)
        else:
            os.makedirs(output_dir, exist_ok=True)
            cq_path = os.path.join(output_dir, f"toffoli_clifft_cq_inc_{args.width}.c")
            with open(cq_path, "w") as f:
                f.write(cq_content)
            print(f"Written: {cq_path}")

            ccq_path = os.path.join(output_dir, f"toffoli_clifft_ccq_inc_{args.width}.c")
            with open(ccq_path, "w") as f:
                f.write(ccq_content)
            print(f"Written: {ccq_path}")
    else:
        # Full generation mode
        if args.dry_run:
            for w in range(1, max_width + 1):
                print(f"// === FILE: toffoli_clifft_cq_inc_{w}.c ===")
                print(generate_cq_inc_width_file(w))
                print()
                print(f"// === FILE: toffoli_clifft_ccq_inc_{w}.c ===")
                print(generate_ccq_inc_width_file(w))
                print()
            print("// === FILE: toffoli_clifft_cdkm_dispatch.c ===")
            print(generate_dispatch_file(max_width))
        else:
            os.makedirs(output_dir, exist_ok=True)

            # Write CQ inc files
            for w in range(1, max_width + 1):
                cq_content = generate_cq_inc_width_file(w)
                cq_path = os.path.join(output_dir, f"toffoli_clifft_cq_inc_{w}.c")
                with open(cq_path, "w") as f:
                    f.write(cq_content)
                print(f"Written: {cq_path}")

            # Write cCQ inc files
            for w in range(1, max_width + 1):
                ccq_content = generate_ccq_inc_width_file(w)
                ccq_path = os.path.join(output_dir, f"toffoli_clifft_ccq_inc_{w}.c")
                with open(ccq_path, "w") as f:
                    f.write(ccq_content)
                print(f"Written: {ccq_path}")

            # Write unified dispatch file
            dispatch_content = generate_dispatch_file(max_width)
            dispatch_path = os.path.join(output_dir, "toffoli_clifft_cdkm_dispatch.c")
            with open(dispatch_path, "w") as f:
                f.write(dispatch_content)
            print(f"Written: {dispatch_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
